### ISSUE TITLE
How to display images within a box?

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1003]
I need to display static images (one after another) within a horizontal box. When I try to do so using `canvas.Image` or `canvas.Raster` they are simply not displayed. When using `widget.Icon` they are drawn super-tiny and I didn't find any way to control their size.

**Comment by andydotxyz** [comment]
Icons are drawn at a fixed (theme set) size, that is their purpose. Images and tasters (due to the nature of a scalable toolkit) have no default size (unless you specify FillMode=ImageFillOriginal - which may create different sizes depending on your screen type). 

Combine this with the fact that HBox is designed to collapse items horizontally to pack them in results in no visible content. You probably want to either set a sensible MinSize for your images, or use a different layout / container.

**Comment by andydotxyz** [comment]
Is there anything more you need for us to close this issue?

**Comment by ababo** [comment]
Thank you for clarification, closing the issue.
