### ISSUE TITLE
Clean up error handling

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#105]
We should consistently deal with errors.
Currently some are ignored, some logged and some returned.

This ticket should start with a discussion about the right approach...

**Comment by glyn** [comment]
I would say the crucial thing is for users to be able to find the root cause of errors, so capturing file and line number at the point at which an error is initially detected would be good. A stack trace can be very useful, but that isn't currently encouraged in Go. It's helpful to log errors that are "swallowed", even if only when detailed logging is enabled.

It may be helpful to compare a recent [Go error proposal](https://go.googlesource.com/proposal/+/refs/changes/97/159497/3/design/XXXXX-error-values.md).

**Comment by andydotxyz** [comment]
One assumes that having something like fyne.Error(level, error) might be the trick - we can extract the info from the runtime stacks and do the appropriate thing.
I think that differentiating between warn/error/fatal is still useful so we can then log and/or quit (or cleverer things later)?

**Comment by glyn** [comment]
> I think that differentiating between warn/error/fatal is still useful so we can then log and/or quit (or cleverer things later)?

Maybe, but sometimes the severity of an error depends on the caller's point of view and is not necessarily known when the error is first detected.

**Comment by andydotxyz** [comment]
That is a good point - but equally we can't really determine that it never really matters or always is problematic... not sure!

**Comment by andydotxyz** [comment]
How about this as a fit for now? We can expand it later with possible LogFatal and/or LogDebug (suppressed by default).

https://github.com/fyne-io/fyne/compare/105-error-handling?expand=1

**Comment by andydotxyz** [comment]
Made it a PR - #152
