### ISSUE TITLE
Android apps from develop use unsupported targetSDK

### ISSUE THREAD

**Issue by yms2772** [fyne-io/fyne#1057]
### Describe the bug:

If I set targetSdkVersion like `<uses-sdk android:minSdkVersion="17" android:targetSdkVersion="28"/>` in `AndroidManifest.xml`, it shows `manual declaration of uses-sdk in AndroidManifest.xml not supported` error.

Is there any solution to change the target sdk version?

**Comment by andydotxyz** [comment]
Currently this is not supported, as the toolkit only supports SDK 16 and above, so we enforce this.
What SDK level were you looking to change it to and for what reason?

**Comment by yms2772** [comment]
> Currently this is not supported, as the toolkit only supports SDK 16 and above, so we enforce this.
> What SDK level were you looking to change it to and for what reason?

The sdk version must be 28 or higher according to the Play Store policy.

**Comment by andydotxyz** [comment]
Ah right yes. We should be using 28 for that reason. Unfortunately that will break notification support (or not compile, I cannot remember).
Look at: https://github.com/fyne-io/fyne/commit/2089b56750393c426931bd5d34dcda972062f836#diff-fbfe0a5f199d872973671309bf6071db

It was downgraded because 26+ requires a newer notifications API that I could not get working in the previous PR. Apologies I forgot about this and we will have to fix the issue.

**Comment by andydotxyz** [comment]
Working on this now. It should be easier to solve this with the working notifications to build upon :)

**Comment by yms2772** [comment]
I see, thank you :) At the end of the year, the policy is to change the sdk version to 29+. If users can flexibly modify this, it will be easier to register on the Play Store.

**Comment by andydotxyz** [comment]
The fix this time is pending review now on develop branch.

In this situation if you had been able to set it to 29 manually then it would have caused notifications to silently fail. We will have to keep up with Google so that the ever increasing review requirements are met with point releases - that way we know that the toolkit is working as expected.
