### ISSUE TITLE
Is there any way to remove default title bar?

### ISSUE THREAD

**Issue by newtorn** [fyne-io/fyne#1078]
I want to remove the default title bar and create a custom title bar. It is to provide a consistent title bar for all platforms. Is there any way to do that?

**Comment by andydotxyz** [comment]
What do you mean by the title bar? All components should look the same across platforms so I don’t understand.

**Comment by newtorn** [comment]
![image](https://user-images.githubusercontent.com/43400069/83793008-7d119700-a6ce-11ea-991b-55d932e0c559.png)
Just like this:
```gtk_window_set_decorated     (GtkWindow *window, gboolean setting);```
Set parm 'setting' to FALSE

**Comment by andydotxyz** [comment]
There is not a directly equivalent API because we think that window management is up to the operating system - windows, Linux and Mac all have different opinions about button placement and then mobile platforms don’t draw at all!

In 1.3 there is a new api to create splash windows as that is a common case where window borders are not expected - those windows would normally hide after a timeout or load completion.

**Comment by newtorn** [comment]
Thank you very much! I got it.
