### ISSUE TITLE
File picker should implement io.Seeker to comply with os.File

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1164]
### Is your feature request related to a problem? Please describe:
The standard library for go has the os.File type for handling a lot of file related functions. It implements the io.Seeker function for seeking the contents. Due to being widely used, a bunch of libraries out there rely on the io.Seeker interface. However, the file picker does not implement it and thus can’t directly be used in those situations.

### Is it possible to construct a solution with the existing API?
I think that would be the case. It might be a bit weirdly worded to have the callback named URIReadCloser when it incorporates a seeker too, but that’s not a huge deal and could possibly be changed in 2.0.

### Describe the solution you'd like to see:
The os.File type is often used to open files and that is basically what we are doing with the file picker too. Because of this we should be compatible where an os.File could be used as we are also working with files. We could either implement Seeker() as is or extend os.File to work in our favour as the URI implementing for files.

I do know that not all URIs will be files, but I cannot see much reason for not selecting a file in a file picker ;)

**Comment by andydotxyz** [comment]
> I cannot see much reason for not selecting a file in a file picker ;)

There is no guarantee that the return from filepicker will be a ‘file://‘ - android and iOS can already return data streams instead of files and in the future we could be connecting to web services or other data source.

To add Seeker would mean implementing g that functionality into the iOS and android file pickers and every type of data source in the future... I’m not sure that we can guarantee that is possible but maybe I’m wrong. We certainly can’t match the File API as that exposes things like Chdir() and Chmod() etc.

**Comment by andydotxyz** [comment]
As we have discussed more recently the file picker can return non-files either through mobile content delivery (other apps streaming data in) or through future HTTP/FTP integration. 
So I don't think we can deliver on this request.
