### ISSUE TITLE
Entry not responding to key events

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1194]
Sometimes my enabled text entry behaves like disable, i.e. doesn't allow to enter symbols. In the log I get:
```
2020/07/17 10:42:22   At: C:/msys64/home/ababo/go/pkg/mod/github.com/inspera/fyne@v1.3.3-0.20200716105309-570475882696/internal/driver/glfw/window.go:1093
2020/07/17 10:42:22 Fyne error:  EventQueue full, perhaps a callback blocked the event handler
```
Fyne: 5cfe49a
OS: Windows 7 (6.1)
Golang: 1.14

**Comment by andydotxyz** [comment]
Is it possible that you are doing some intense computation in a key callback?
That error appears if the toolkit is not able to process the key presses - which is usually caused by developer code blocking the processing of events.

**Comment by ababo** [comment]
Nope, at this moment nothing happens, the form just waits for user to enter text.

**Comment by ababo** [comment]
The key callback just constraints the line width and enables a button:
```go
func handleTestPinChange(ctx *pinPageContext) {
	if len(ctx.pin.Text) > testPINMaxLen {
		ctx.pin.SetText(ctx.pin.Text[:testPINMaxLen])
	}

	if len(ctx.pin.Text) < testPINMinLen {
		ctx.unlock.Disable()
		return
	}

	ctx.unlock.Enable()
}
```

**Comment by ababo** [comment]
Sometimes no messages are written in the log, but still entries behaves like disabled.

**Comment by ababo** [comment]
Yes, the messages in the log appear when I try to press on the disabled entry many times.

**Comment by andydotxyz** [comment]
If `handleTestPinChange` is called from an OnChange handler you might be creating an issue - as you are changing the content again...

It's difficult to understand how that code is being executed, and where it's hooked in could make a big difference.
Is it possible to share a full, but minimal, code sample with steps to replicate?

**Comment by ababo** [comment]
Yes, this is an OnChange handler and it will be called recursively on `SetText`. I don't see any problem with that here (try to follow the code logic). I'm afraid this problem is linked with #1190, I need to investigate it more.

**Comment by andydotxyz** [comment]
In #1190 you did not mention any error output. If it does indeed list that the event queue is full then this is a duplicate. If it does not then they may be separate issues.

Unfortunately without a way to replicate the error I'm a bit stuck on helping further. The most likely issue would be some of your application code blocking in a callback of some sort, so if you're able to debug then it might be worth seeing what state the goroutines are in. We have 3 that are marked as locked to system threads - the main thread ("0"), the draw thread and the event thread - so a stack trace may highlight them for you, the issue is likely with one of the latter two.

**Comment by ababo** [comment]
I have figured out what was happening. Due to double-pressing a button handler was blocked on non-buffered channel. That prevented Fyne thread handling the rest of the widgets. Closing.

**Comment by andydotxyz** [comment]
I assume that channel was in your code? If it’s in Fyne sounds like something we need to fix.

**Comment by ababo** [comment]
No, that was mine.
