### ISSUE TITLE
support chinese characters

### ISSUE THREAD

**Issue by easykoo** [fyne-io/fyne#120]
does not display chinese characters yet

**Comment by andydotxyz** [comment]
This might be a duplicate of #63. You can show chinese characters by loading a font that supports them. Due to the file sizes I don't think we can embed all of the fonts for every language - but a more streamlined setup for these languages / locales might help.

Does FYNE_FONT solve your issue or do we need to find a better solution?

**Comment by andydotxyz** [comment]
Closing this as other reports say this is resolved
