### ISSUE TITLE
Why can't you write styles in components like Flutter?

### ISSUE THREAD

**Issue by xfengw** [fyne-io/fyne#1230]
### Is your feature request related to a problem? Please describe:

Hopefully, You want to write a style in a component, just like flutter.

**Comment by andydotxyz** [comment]
In essence this is because we have taken different design decisions than the Flutter project.
The Fyne API is based on semantic outcome - a widget API is about it's logic and state rather than visual appearance.
The rendering of a widget is handled by it's (private) renderer according to the current theme.
This approach means that applications can look different by using the theme and other graphical elements but that the interactive elements (widgets) will always be consistent.

As there is a canvas API you can, with work, build any custom widget or style - but we are not including such customisation in the Widget API.
