### ISSUE TITLE
For `NewRaster`, please provide single `Resize` event before hitting `pixelFunc` with goroutines

### ISSUE THREAD

**Issue by gmlewis** [fyne-io/fyne#126]
When using a `pixelFunc` with `canvas.NewRaster`, the only way to tell that the raster size has changed is by saving the `w` and `h` parameters since the last call, and if they are different, you can then recalculate the full raster for a complex image (see #123 for related issue).

But because `pixelFunc` is being hit concurrently with multiple goroutines, it needs to use a `sync.Mutex` on each and every call to prevent the raster recalculation from occurring multiple times for a single resize.

This incurs a large performance hit.

Instead, if a settable `Resize` callback were provided, `fyne` could make a single `Resize` call immediately before calling the first `pixelFunc` (only when needed, of course... that is, when the actual `Canvas` size has changed) and thereby let the `pixelFunc` run at full speed.

**Comment by andydotxyz** [comment]
There is a lot of activity on this in the Slack channel but I wanted to report back here.
As a primitive type adding callbacks does not make a lot of sense.

That said the NewRaster was probably aimed very specifically aimed at runtime generated images rather than something that has a backing store for slower rendering operations.

There is an effort under way (thanks @jadr2ddude) to change the default raster implementation to better support a single call per image refresh. The more dynamic pixel callbacks could be added on top of this if it were still wanted.

**Comment by andydotxyz** [comment]
It seems that we can close this. The new NewRaster() now uses a callback that is once per complete-refresh so should provide what you want.
The old version is now NewRasterWithPixels() (though we are working out how to get the concurrency back in without massive overheads in pixel conversion).
