### ISSUE TITLE
Add the ability to choose a new file but not create it using a FileDialog

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1264]
### Is your feature request related to a problem? Please describe:
I am writing an application where the user can specify where a certain file should be created. But this file will be created when the user presses the **Create** button and not when the dialog is closed. Currently the user chooses where to store the file and immediatly the file will be created without any content. Now if the user does not decide to create the file. There's just an empty file lying around.

### Is it possible to construct a solution with the existing API?
I didn't find a different dialog that supports this. You could use the FileOpenDialog, but it is limited to files that already exist. You could also just delete the file when the user closes the window or something, but that's not the correct way to do it.

### Describe the solution you'd like to see:
Either add a new function to FileSaveDialog like ```func SetShouldCreateFile(shouldCreate bool)``` or something or create another FileDialog. If the FileSaveDialog solution is done, the URIWriteCloser should be closed and just contain the name and path of the file. Either implementation would be appreciated.

**Comment by andydotxyz** [comment]
The way that file abstraction works in Fyne is a little complicated so that we can support cross-platform functionality. The dialog is opening a writer to the location that the user specified and needs special permissions on some systems to do this, so to make things smooth the writer is returned so that data can be written immediately.
The workflow of not actually writing but doing so later would require apps built for iOS to request additional permissions and would not be able to support the full choice available using the OS provided destination chooser.

Perhaps you could expand more on what the requirement is for chosing a file and at some later date creating it? At the moment I would imagine that you could instead initiate the ShowFileSave dialog when tapping the "Create" button in your application. The user can still cancel the process from the dialog if they change their mind...

**Comment by PucklaMotzer09** [comment]
I understand that it is compilicated when considering multiple platforms. In my application you can create an image. You can configure some properties that influence the image. So it would be annoying to always need to choose the file location when clicking on **Create**. I want to keep the functionality that you can choose the file location seperately to the creation of it. But as it seems this will not be implemented so I just have to find a way around it.

**Comment by PucklaMotzer09** [comment]
My current workaround:
```go
if err = os.Remove(fileName); err != nil {
	fmt.Fprintln(os.Stderr, err)
	return
}
```
This is how I get the file name (also a workaround):
```go
fileName := writer.URI().String()
fileName = fileName[7:]
```

Since my application will only be used on windows, this should be no problem.

**Comment by andydotxyz** [comment]
How would it be if you chose the file location the first time, then in future writes you re-request a write to the URI stored from the fist attempt? You need not ask the user for the location a second time (like the difference between "Save" and "Save As...".

In the future we may add support for "ftp://" or "webdav://" for example, at which point even a windows-only app would benefit from using the abstraction we've provided.

**Comment by PucklaMotzer09** [comment]
> How would it be if you chose the file location the first time, then in future writes you re-request a write to the URI stored from the fist attempt?

Unfortunately this is not possible, since I am using ```gonum.org/v1/plot```.  This library only supports file names and not ```io.Writer```. Otherwise this would be the solution I am going for.

**Comment by andydotxyz** [comment]
Try using `plot.WriterTo` instead of `plot.Save`
