### ISSUE TITLE
Using Fyne with another application in OpenGL

### ISSUE THREAD

**Issue by rishabh-bector** [fyne-io/fyne#128]
Hello fyne devs,

I'm working on a game engine written in Go, and I'm using the go-gl bindings as OpenGL is my main rendering backend. I came across Fyne the other day, and I think it's a really cool project! I really like how easy it is to use, and I think what you guys are creating is awesome. I'd love to be able to use Fyne to create a UI system for my application in Go, however I'm unsure of how to go about doing it. 

I'm using go-gl v4.1-core in my engine, and I'm using GLFW for window management. Would it be as simple as pointing Fyne towards my GLFW window instead of whichever one it creates? Regardless, I was wondering if there is a way that you know of to easily integrate Fyne as a UI for an application which is already using OpenGL, such as a game.

If you are interested, my game engine is here: https://github.com/rishabh-bector/rapidengine

Have a fyne day,
Rishabh

**Comment by andydotxyz** [comment]
Hi,

That project looks really cool, well done!
In theory it would be possible to do what you are looking to - but right now it is not.

Complexities: 
* A fyne driver creates a window for each canvas that it will manage
* The event loop occupies the main thread (also glfw)
* The input events would need to be shared between two applications somehow.

At this time I don't know how you would go about it - the event loop and input mechanism would need to be spliced with your own and after that a new method of creating a canvas inside an existing context would be needed.

This is outside the scope of the project, but I don't want to close the issue as it would be interesting to see if you were able to come up with a solution that we could integrate :)

**Comment by mfisher31** [comment]
Hi guys, I'm in the same boat.  Was wanting to use fyne to make LV2 plugin gui's.  Can't do it without a way to manually run the event loop.  Also would need fyne to provide access to the Native X11 window, NSView, or HWND pointers.

Most GUI toolkits provide these kind of mechanism, and it would be awesome to see fyne do the same.

**Comment by andydotxyz** [comment]
Thanks @mfisher31 the Fyne toolkit is aiming to be an abstraction to hide the complication of native GUIs. As we handle X/win/Darwin/android/iOS providing OS level pointers significantly reduces the toolkit usefulness. Is there something we can do to provide abstracted access to low level features that could help?

I’d love to know more about what you want to do and how native window access is important to completing the feature?

**Comment by mfisher31** [comment]
@andydotxyz - [LV2](http://lv2plug.in) is the leading audio plugin standard for Linux.  Plugins and UIs are compiled as shared libraries and loaded by hosts like [Ardour](http://ardour.org)

Access to these objects is merely so the host can load a plugin's GUI and embed it into its own GUI not worrying about which toolkit the plugin UI is written in.  Having an accessor to the native widget makes this possible. Allowing manual control of the event loop makes it so the LV2 host can drive the GUI from within it's own main loop.

Without the latter, `app.Run()` would block main and cause nasty things to happen in the host.  Something like `app.DistpacthEvents()` would be killer.  This would be driven from hosts/uis supporting [LV2 Idle Interface](http://lv2plug.in/doc/html/group__ui.html#structLV2UI__Idle__Interface).

I'd love to jump in and see if I could even make this work even if just proof of concept.  Any tips on where to look in the code to test some stuff out?

And just to clarify, client code wouldn't be modifying the native handle in any kind of way.  It's just so that host applications can show/embed plugin GUI's.

Hope all that makes sense.  I'm still new to Go in general, but well versed in LV2 http://github.com/lvtk < my lv2 projects.  I have some go projects in the works which can compile an LV2 UI with Go and bind to the C Api, but having nothing in terms of creating the actual GUI part (go packages haven't been pushed to github yet)

**Comment by mfisher31** [comment]
Oh, and I haven't found any other GO UI toolkit that do what is needed.  Except for maybe Nuklear... but if I'm going that lowlevel, I'll just do it in C/C++ :)

**Comment by andydotxyz** [comment]
Thanks for the information, it makes sense. If we can do this just by allowing manipulation of the runLoop this may be possible. This would mean that the Fyne portion opened it's own window to run the GUI - is this OK?
If you need to literally embed the graphical components into another UI this gets much more complicated, though not impossible :)

For runloop related work then you may have some success in looking into fyne/internal/driver/glfw/loop.go and the interface it implements in fyne/driver.go. To look at access to native surfaces would require learning glfw and gomobile to see what is possble and then figure out how that could be accessed through (platform specific? like fyne/driver/desktop) the Fyne interfaces.

**Comment by mfisher31** [comment]
No problem.  I did some digging and experimenting.  Turns out glfw itself will only create/allow access to the top-level window.  When I try to embed in another app, a nasty crash happens.  Is it possible to make custom drivers?  I have a hunch [pugl](https://github.com/drobilla/pugl) could be used since it has the ability to create a native widget without a toplevel window (already have Go bindings in progress and working)

Would still need a manual way to drive the event loop.  Also did some experimenting here too. Seems feasible to do without altering the normal `Run` api.  Essentially, `Run` could call the same methods used for manual event processing, but inside it's own timer.

Anyhow, I'm excited to get this working and blow some minds by writing LV2 guis in golang 😃

**Comment by andydotxyz** [comment]
This has been open for a while and I think the solution of a custom driver makes sense.
The GL painter has been refactored out, though it is an internal detail at the moment.
Re-open this issue if you would like to progress this and explore how to make the most of code re-use along the way.

**Comment by mrjrieke** [comment]
@andydotxyz , is fyne-x updated to 1.2 yet?

**Comment by andydotxyz** [comment]
No, @damien-lloyd there has been no progress on this closed issue.
