### ISSUE TITLE
Default window size

### ISSUE THREAD

**Issue by VBQL** [fyne-io/fyne#134]
Is there a way to define the window to per say, 500px x 500px?

The issue is that the "title name" gets replaced by "ti..." when there isn't enough things within the window to show the whole thing. In order to have the window show the full title name I either have to resize after launching or add elements. Is there a variable I can declare to solve this?

Thanks!

**Comment by andydotxyz** [comment]
Fyne launches windows in the smallest size to pack in all the content, unless told otherwise.
Window.Resize() can be called before Window.Show() - if you have trouble doing that then please raise an issue.
The other approach is to increase the minimum size of an element in your content.

So the answer to your main question question is "Yes - use Window.Resize()" but I'm not sure that fuly answers your dilemma?

**Comment by VBQL** [comment]
Thanks! That solves the issue.
