### ISSUE TITLE
Delete/Rename URIs

### ISSUE THREAD

**Issue by squash** [fyne-io/fyne#1509]
### Is your feature request related to a problem? Please describe:
Currently there is no straightforward way to remove or rename a file by URI.

### Is it possible to construct a solution with the existing API?
I am implementing a hacky solution that breaks the URI apart into a normal file path, does the required operation, and then (for renames) parses a new URI. 

### Describe the solution you'd like to see:
It would be nice if this functionality were included as part of the URI type

**Comment by andydotxyz** [comment]
Indeed. Let's get these in. We could not add them easily in 1.4 as it would be a breaking change in the URI type - so we will pop it in 2.0

**Comment by charlesdaniels** [comment]
I have rolled this into #1665. I think adding delete functionality via `URI.Destroy()` is a good idea, but I'm not sold on `Rename()`, as this merely composes several existing operations (create, write, delete). On the other hand, exposing this to the underlying implementation as a `Rename()` operation may allow for optimizations (e.g. doing the rename on the remote end, rather than pulling the data down and writing it back over the wire for a remote fs).

Thoughts?

**Comment by andydotxyz** [comment]
All good points I guess.
Worth noting that if we don't add Rename now it cannot appear until 3.0 as it will break the URI API.
Doing that inside the app is indeed possible - but could produce bad intermediate states (like create, write, delete where delete fails leaves duplicates...).

Not sure that I prefer Destroy() over Delete() though (we use it internally to free memory which I think is different.
Usually the choice is between Delete and Remove.

**Comment by andydotxyz** [comment]
Landed, great job thanks @charlesdaniels and the team.
