### ISSUE TITLE
Custom dialog does not display image

### ISSUE THREAD

**Issue by Uldiniad** [fyne-io/fyne#1559]
### Describe the bug:

I am using trying to use a screenshot (static resource) in a dialog and I cannot get it to display. I have verified that fyne can display the image in other scenarios (e.g. window.setContent)

### To Reproduce:
Steps to reproduce the behaviour:
1. Bundle a jpg as a static resource
2. Make a canvas image object referencing that static resource
3. Make a custom dialog and set its content to the canvas image object

### Screenshots:

![image](https://user-images.githubusercontent.com/17321823/99298424-ae62c700-2817-11eb-9676-a2b1541f4212.png)
The space between the dismiss button and the text is where the image should be displaying

### Example code:

```go
bootloaderWarning := dialog.NewCustom("Warning", "OK", container.NewVBox(canvas.NewText(line, color.Black), screenshot), window)
bootloaderWarning.Resize(window.Content().Size())
bootloaderWarning.Show()
```

### Device (please complete the following information):
 - OS: Windows
 - Go version: 1.15.4
 - Fyne version: 1.4.0

**Comment by andydotxyz** [comment]
Images have a 0, 0 MinSize due to the mismatch betweeen pixel and scalable coordinates.
The dialogs normally minimise content to minsize.
Unfortunately your usage of `container.NewVBox` is keeping it squashed down as that layout does not expand content above it's minimum size. Try using `container.NewBorder` instead, as that will expand the content.
(you can test this out by temporarily passing the image only as the content).

P.S. use `widget.NewLabel(line)` instead of `canvas.NewText(line, color.Black)` as that will correctly match the loaded theme.

**Comment by Uldiniad** [comment]
suggestions worked. thank you 👍
