### ISSUE TITLE
`SetMinSize()` on anything with a `MinSize()`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1581]
### Is your feature request related to a problem? Please describe:
Currently, I find myself "extending" widgets literally only to override the `MinSize()`

Examples include `List` and `Table` when used in any compacting layout.

### Is it possible to construct a solution with the existing API?
Perhaps I don't understand this question.

### Describe the solution you'd like to see:

```golang
	t := time.Now()
	data := []struct{ Name, Size, Format, Created, Updated, Accessed string }{
		{"index.html", "21.4 KiB", "text/html", t.AddDate(0, 0, -2).String(), t.AddDate(0, 0, -1).String(), t.String()},
	}

	createLabel := func() fyne.CanvasObject {
		label := widget.NewLabel("X")
		label.SetMinSize(fyne.NewSize(100, 20))
		return label
	}

	list := widget.NewList(func() int { return len(data) }, createLabel, func(lii widget.ListItemID, f fyne.CanvasObject) {
		f.(*widget.Label).Text = data[lii].Name
	})
	list.SetMinSize(fyne.NewSize(200, 100))

	table := widget.NewTable(func() (int, int) { return len(data), 6 }, createLabel, func(tci widget.TableCellID, f fyne.CanvasObject) {
		atom := data[tci.Row]
		switch tci.Col {
		case 1:
			f.(*widget.Label).Text = atom.Name
		case 2:
			f.(*widget.Label).Text = atom.Size
		case 3:
			f.(*widget.Label).Text = atom.Format
		case 4:
			f.(*widget.Label).Text = atom.Created
		case 5:
			f.(*widget.Label).Text = atom.Updated
		case 6:
			f.(*widget.Label).Text = atom.Accessed
		}
	})
	table.SetMinSize(fyne.NewSize(600, 300))

	w.SetContent(container.NewVBox(
		widget.NewCard("Title", "Subtitle", list),
		widget.NewCard("Title2", "Subtitle2", table),
	))
```

**Comment by andydotxyz** [comment]
The Minimum size of any widget is defined as the size which it cannot be smaller than. This is essetial for laying out complex layouts whilst allowing users to resize windows up or down. Whhen you change the MinSize of an item it cannot become smaller. This is a big problem when scaling down to small screen sizes, like for mobile devices.

Table cells and items of List and Tree are special - they are sized based on the template MinSize. Instead of using your desired MinSize hack you should set an indicative template value instead:
```
		label := widget.NewLabel("Average string")
```
That is how they are designed.
In v1.4.1 there is an additional `Table.SetColumnWidth` that gives more fine-grained control.

For all elements their actual size is set by the container as a result of various calculations.
If you do not want your widget to shrink do not put it in a layout that shrinks the content.
There are various layouts available or you can provide your own.

* https://developer.fyne.io/started/layouts
* https://developer.fyne.io/tutorial/custom-layout

**Comment by AlbinoGeek** [comment]
Right, but this also is the issue of `Table` and `List` currently have a `MinSize` that is **less than one template element tall** -- resulting in an unusable table/list when put inside a compacting layout such as `VBox` or `Card`.

**Comment by andydotxyz** [comment]
Developers choose the layouts in containers as well as the widgets that get put in them - so can you apply a layout that expands the component you would like to be larger?

Without more concrete example or description of what cannot be done with the current design it is difficult to provide a more constructive solution, sorry.

**Comment by stuartmscott** [comment]
> Table and List currently have a MinSize that is less than one template element tall

@andydotxyz there is an inconsistency here:
```go
func (l *listRenderer) MinSize() fyne.Size {
	return l.scroller.MinSize()
}

func (t *tableRenderer) MinSize() fyne.Size {
	return t.cellSize
}

func (r *treeRenderer) MinSize() (min fyne.Size) {
	min = r.scroller.MinSize()
	min = min.Max(r.tree.branchMinSize)
	min = min.Max(r.tree.leafMinSize)
	return
}
```
I think Tree does it correctly

**Comment by andydotxyz** [comment]
There will be some inconsistency, but you're right these have deviated too far.
`List` does have the correct width - it is set indirectly by the `Scroll` being in vertical-only mode.

Possible changes:
* List minHeight to be equal to template item height
* Table minHeight and minWidth to match the template cell

That will fix up the inconsistency I think.

**Comment by AlbinoGeek** [comment]
^ Agreed, at least that would make them usable in a compact layout.

Currently, `Table` inside `VBox` gives you a `.5` height and (seemingly unrelated) width.

**Comment by andydotxyz** [comment]
Looking into this further @stuartmscott, I think that `Table` is calculating it correctly - I thought it was maybe missing padding but seems not.
List min height may still be wrong.

I have re-run the image tests requesting that tables be minimum size, and they come out as expected...
![theme_initial](https://user-images.githubusercontent.com/294436/99733979-edb04280-2ab9-11eb-9d85-19ac4d3a4ca6.png) - so I don't know what issue you are hitting @AlbinoGeek but it does not seem to be caused by `Table.MinSize()`

**Comment by AlbinoGeek** [comment]
@andydotxyz 

![image](https://user-images.githubusercontent.com/1910461/99734492-b7ea6a00-2a77-11eb-92b1-f94873e5808d.png)

```golang

	data := [][]string{
		{"Foo", "Bar", "Baz"},
		{"Foo", "Bar", "Baz"},
		{"Foo", "Bar", "Baz"},
	}
	table := widget.NewTable(
		func() (int, int) { return len(data), len(data[0]) },
		func() fyne.CanvasObject {
			return widget.NewLabel("@@@")
		},
		func(tci widget.TableCellID, f fyne.CanvasObject) {
			f.(*widget.Label).SetText(data[tci.Row][tci.Col])
		},
	)

	tc := container.NewAppTabs(
		container.NewTabItem("Table Issue",
			container.NewVBox(
				widget.NewCard("Title", "Subtitle", table),
			),
		),
	)
	w.SetContent(tc)
```

**Comment by stuartmscott** [comment]
@AlbinoGeek thanks for sharing this code

@andydotxyz, @okratitan the collections should all return `scroller.MinSize().Max(cell|item|branch|leaf.MinSize())`

**Comment by andydotxyz** [comment]
Aha! Thanks @AlbinoGeek looks like this is a Card Min/Size/Layout bug!
I can get that fixed in the morning

**Comment by andydotxyz** [comment]
The bug reported is now fixed on `release/v1.4.x`, and will be available in v1.4.2 in a few weeks.
Please test it and let me know if we can mark this ticket is resolved now @AlbinoGeek.

**Comment by AlbinoGeek** [comment]
Just noticed that `canvas.Text` has a `SetMinSize` and also draws at the correct baseline, where `widget.Label` does not.

**Comment by andydotxyz** [comment]
the correct baseline is only true as long as you don't expand the height of the text I think?
Because it is rendering only the pixels necessary. It has no vertical alignment so it's your usage of it that is correctly aligning, rather than the text ;)

**Comment by andydotxyz** [comment]
SetMinSize is required for Text and Image because the driver will discover the minimum size when it actually renders (due to font loading or image parsing).
In this regard canvas primitives are different to widgets - they don't really have implicit minimum (i.e. how big should a line be) so it allows the minimum setting.

**Comment by AlbinoGeek** [comment]
Gitcha! I can then say this is now fixed, save for the vertical baseline issue [covered elsewhere]. #1016 ?

**Comment by ivoras** [comment]
Resurrecting this issue because the logic doesn't apply neatly to dialogs. 

![image](https://github.com/fyne-io/fyne/assets/2300424/6467ec6a-8fc6-47ab-8cd4-53687c82e85c)

The password entry is too small, and there's no SetMinSize() to correctly size it.

**Comment by Jacalz** [comment]
@ivoras Please don’t resurrect old issues that have been closed. It is better to open a new issue or a discussion depending on the context. In this case however, there is a `.Resize()` method on the dialog and that will solve your issues mentioned above.
