### ISSUE TITLE
[FEATURE REQUEST] Remove `Quit` from MainMenu

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1596]
### Is your feature request related to a problem? Please describe:
https://github.com/fyne-io/fyne/issues/1595 - [REGRESSION] After 1.4.1 `MainMenu -> Quit` does nothing

Also, there are some programs which have mandatory cleanup and otherwise should not be easily Quit outside of developer control. Currently, the only option to do so is to either not have a MainMenu, manually butcher the menu items after creation, or override `SetMainMenu` etc.

### Describe the solution you'd like to see:
Honestly not sure.

**Comment by AlbinoGeek** [comment]
Other reasons include:

- "Clean Shutdown" Requirement [Subverting or otherwise controlling the Quit.]
- Internationalization Requirement [Changing the text of all labels, menus, etc.]
- Non-Closeable Program Requirement [Parental Controls, Security Software, etc.]

**Comment by andydotxyz** [comment]
This is complex, macOS enforces a quit, mobile apps refuse it - hence why we manage it automatically.
I don't think that we can remove the option to quit an app - it will always be possible even if we hide it.
I think this may relate to #1053 instead.

for "other reasons":

* We already have Window.CloseIntercept that should handle most use-cases
* Internaltionalisation should fix the Quit label through a solution rather than removing standard and putting a different one in
* Such applications should have a background runner app that "cannot close" - the user should not be forced to keep the GUI open.

I think this should be closed as won't-fix, but I'll let you respond to these comments first in case I missed something.

**Comment by AlbinoGeek** [comment]
Good to know, this is legitimate reasoning for sure. -- Given the linked problem is no longer a thing, this should be alright.
