### ISSUE TITLE
Design reconsideration request

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#1640]
Hi,
i just like to point out that the new design does not look that good, i don't know what's wrong with it, but the light theme is too white
and in the dark theme the borders of elements (buttons, list, etc...) is too dark and they are hard to catch...

i would ask you to reconsider the design :) 

thank you for your time

**Comment by andydotxyz** [comment]
Can you suggest some alternatives? Design is such a subjective concept.
We are using the pallette generated by the Material UI Theme Generator at https://cimdalli.github.io/mui-theme-generator/

**Comment by AlbinoGeek** [comment]
I don't think that site's (default) theme even matches that of Material Design, blue and pink?

That being said, after changing a few things around, I see these discrepancies:

### `fyne` Dark Theme
```
	theme := &builtinTheme{
		background:     color.NRGBA{0x30, 0x30, 0x30, 0xff},
		button:         color.Transparent,
		disabled:       color.NRGBA{0xff, 0xff, 0xff, 0x42},
		disabledButton: color.NRGBA{0x26, 0x26, 0x26, 0xff},
		text:           color.NRGBA{0xff, 0xff, 0xff, 0xff},
		placeholder:    color.NRGBA{0xb2, 0xb2, 0xb2, 0xff},
		hover:          color.NRGBA{0xff, 0xff, 0xff, 0x0f},
		scrollBar:      color.NRGBA{0x0, 0x0, 0x0, 0x99},
		shadow:         color.NRGBA{0x0, 0x0, 0x0, 0x66},
	}
```

### `MUI` Dark Theme

```
		background:     OK
		button:         OK
		disabled:       NOK      0x42 == dec 66 (0.25) [MUI says 30]
		disabledButton: NOK      same issue as disabled
		text:           OK
		placeholder:    NOK      same issue as disabled
		hover:          NOK      [MUI says `(153,153,153,0.2)`]
		scrollBar:      unknown
		shadow:         NOK      0x66 == dec 102 (0.4) [MUI says `(0,0,0,1)`]
```

## Differences

| Prop | `fyne` | `MUI` |
|-|-|-|
|`disabled`|`(255,255,255,0.25)`|`(255,255,255,0.3)`
|`disabledButton`|`(38, 38, 38, 0.25)`|`(43, 43, 43, 0.3)`
|`placeholder`|`(178,178,178,1)`|`(255,255,255,0.3)`
|`hover`|`(255,255,255,0.06)`|`(153,153,153,0.2)`
|`shadow`|`(0,   0,   0,   0.4)`|`(0,   0,   0,   1)`

---

[ Do tell me if I've converted something wrong. ]

**Comment by s77rt** [comment]
Hi,
i really can't help much regarding the design, but i would suggest to extend the theme structure,
i think we need to be able to set a custom text, color for each widget
if you try and change the button background color you will notice that also the background of the list widgets will be changed too.
and you can't even set a different text color for the button without changing the whole app text color
that and the need to change the colors as i don't think they are the ones that material.io defines as default light and dark themes.

also perhaps it would be better to have 4 defaults themes instead of 2:
lighter (bg: ffffff)
light (bg: f2f2f2)
dark (bg: 2d2d2d)
darker (bg: 121212)

**Comment by AlbinoGeek** [comment]
@s77rt 

You can create a label with a custom text colour by doing this:
```golang
	t := canvas.NewText("Label", color.NRGBA{0xff, 0x0, 0x0, 1}) // red label
```

Changing the background colour of individual widgets is **already deprecated**, and with the renderer reference not being kept around anymore (reading the comments on Widget and WidgetRenderer) I have to assume this functionality simply won't be available in the future.

I previosuly thought that this was an important feature, but it turns out, you don't really need different background colours normally when it comes to a program's interface, as it's simply confusing for the user.

Exception: Rich Text Editors , but that's in another issue.

If you want a coloured square (such as, putting this behind a widget to change its background):
```golang
	r := canvas.NewRectangle(color.NRGBA{0x0, 0x0, 0xff, 1}) // blue square
	r.Resize(fyne.NewSize(5, 5))                             // and it's 5x5
```

---

When it comes to defining your own themes, it's actually quite easy once someone gives you a code sample:

Here's code for a theme that loads from a `.yaml` configuration file (using the viper package) -- otherwise returns a darker-than-default theme.

### Usage
```golang
	a.Settings().SetTheme(DarkerTheme())
```

### `types` Code
```golang
package types

import (
	"fmt"
	"image/color"

	"github.com/spf13/viper"
)

// GetColor returns an NRGBA key with the defined prefix, if set -- otherwise
// the color passed in as def is returned instead.
func GetColor(key string, def color.Color) color.Color {
	slice := viper.Get(fmt.Sprintf("%s.r", key))
	if slice == nil {
		return def
	}

	clr := color.NRGBA{
		uint8(viper.GetUint(fmt.Sprintf("%s.r", key))),
		uint8(viper.GetUint(fmt.Sprintf("%s.g", key))),
		uint8(viper.GetUint(fmt.Sprintf("%s.b", key))),
		uint8(viper.GetUint(fmt.Sprintf("%s.a", key))),
	}

	if clr.A == 0 {
		return def
	}

	return def
}
```

### Theme Code
```golang
package gui

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/theme"

	"github.com/spf13/viper"
)

// DarkerTheme is a darker variant of fyne.DarkTheme()
func DarkerTheme() fyne.Theme {
	return &darkerTheme{
		base: theme.DarkTheme(),
	}
}

type darkerTheme struct {
	base fyne.Theme
}

// colors //

func (darkerTheme) BackgroundColor() color.Color {
	return types.GetColor("theme.color.background", color.NRGBA{0x20, 0x20, 0x22, 0xff})
}

func (darkerTheme) ButtonColor() color.Color {
	return types.GetColor("theme.color.button", color.Transparent)
}

func (darkerTheme) DisabledButtonColor() color.Color {
	return types.GetColor("theme.color.disabledButton", color.NRGBA{0x16, 0x16, 0x18, 0xff})
}

func (theme darkerTheme) DisabledIconColor() color.Color {
	return types.GetColor("theme.color.disabled", theme.base.DisabledIconColor())
}

func (theme darkerTheme) DisabledTextColor() color.Color {
	return types.GetColor("theme.color.disabled", theme.base.DisabledTextColor())
}

func (theme darkerTheme) FocusColor() color.Color {
	return types.GetColor("theme.color.focus", theme.base.FocusColor())
}

func (theme darkerTheme) HoverColor() color.Color {
	return types.GetColor("theme.color.hover", theme.base.HoverColor())
}

func (theme darkerTheme) HyperlinkColor() color.Color {
	return types.GetColor("theme.color.primary", theme.base.HyperlinkColor())
}

func (theme darkerTheme) IconColor() color.Color {
	return types.GetColor("theme.color.text", theme.base.IconColor())
}

func (theme darkerTheme) PlaceHolderColor() color.Color {
	return types.GetColor("theme.color.placeholder", theme.base.PlaceHolderColor())
}

func (theme darkerTheme) PrimaryColor() color.Color {
	return types.GetColor("theme.color.primary", theme.base.PrimaryColor())
}

func (theme darkerTheme) ScrollBarColor() color.Color {
	return types.GetColor("theme.color.scrollBar", theme.base.ScrollBarColor())
}

func (theme darkerTheme) ShadowColor() color.Color {
	return types.GetColor("theme.color.shadow", theme.base.ShadowColor())
}

func (theme darkerTheme) TextColor() color.Color {
	return types.GetColor("theme.color.text", theme.base.TextColor())
}

// integers //

func (darkerTheme) IconInlineSize() int {
	return viper.GetInt("theme.iconInlineSize")
}

func (darkerTheme) Padding() int {
	return viper.GetInt("theme.padding")
}

func (darkerTheme) ScrollBarSize() int {
	return viper.GetInt("theme.scrollBarSize")
}

func (darkerTheme) ScrollBarSmallSize() int {
	return viper.GetInt("theme.scrollBarSmallSize")
}

func (darkerTheme) TextSize() int {
	return viper.GetInt("theme.textSize")
}

// fonts //

func (theme darkerTheme) TextFont() fyne.Resource {
	return theme.base.TextFont()
}

func (theme darkerTheme) TextBoldFont() fyne.Resource {
	return theme.base.TextBoldFont()
}

func (theme darkerTheme) TextBoldItalicFont() fyne.Resource {
	return theme.base.TextBoldItalicFont()
}

func (theme darkerTheme) TextItalicFont() fyne.Resource {
	return theme.base.TextItalicFont()
}

func (theme darkerTheme) TextMonospaceFont() fyne.Resource {
	return theme.base.TextMonospaceFont()
}
```

**Comment by andydotxyz** [comment]
Just FYI we have a new Theme API ready for v2, which is available for testing on the `develop` branch already. It is more extensible and flexible than the current release.

If I may @s77rt - I think you have 3 different comments in this ticket:

1) Some of the default colors don't match material design defaults
- this is probably true, the theme has evolved based on previous limitations of the toolkit. v2.0 (January) is a good chance to fix some of these things and we appreciate any input

2) Standard widgets don't support arbitrary colour choices for elements
- yes, this is a design decision. The standard widgets follow the loaded theme. I don't see that making every design element configurable makes for a better default design - we have avoided it because it's easy to make widgets unusable.

3) Some widgets are using the wrong color
- this could be true, please raise these specific instances so we can resolve (or open a PR). It's also worth noting at this time that the background colour of a widget is beign removed, they will be transparent by default so we can do smarter things to highlight in keyboard control etc.

I hope that this is helpful. There are probably some elements where colours could be improved, opening issues when you find them can be helpful, although it might be best to test against the `develop` version for this as the theme code is changing a lot over the following month.

**Comment by andydotxyz** [comment]
Oh, I missed the thought that there should be 4 default themes.
We have picked 2, 1 light and 2 dark, so that we can support the growing preference for one of the other exposed in more OSes.
If you feel it would be useful to allow the user to choose from more themes then please open a new issue requesting this, For now we support 2 builtin and allow app developers to override this for their own purposes. User loaded theming is something that could be supported, but that we haven't really got much request for yet.
