### ISSUE TITLE
How to adjust the font size of the title bar?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#1714]
Hi,I use fyne_demo, and I think the font size is a little too big. How to adjust the font size of the title bar and the sidebar?
![font_size adjust](https://user-images.githubusercontent.com/50661521/103519508-9969f200-4eb0-11eb-8914-f1174213bc36.png)

**Comment by gernotstarke** [comment]
imho that has been dealt with in another SO question:

https://stackoverflow.com/questions/57651536/how-to-change-color-of-gui-components

Title and sidebar belong to the theme, and therefore are not subject to styling.

**Comment by andydotxyz** [comment]
That font looks like a custom one... if you are loading a different font perhaps try another?

**Comment by smp12345** [comment]
Yes, this is a Chinese font, all Chinese fonts are relatively large, it is better to customize the font size, can you change the size?

**Comment by andydotxyz** [comment]
We don't have a setting for changing font size. We had assumed that a 14pt font would be 14pt tall...
There is a user setting for scale (File menu -> Settings) that can also be set on commandline (`FYNE_SCALE=`) however this changes the whole UI scale, not just the font size.

If this is something we have to address to accomodate chinese fonts then we will cover it in our internationalisation work for [v3.0](https://github.com/fyne-io/fyne/milestone/9)

**Comment by smp12345** [comment]
Look forward to V3.0 and hope that you can pass a parameter to change the font style, such as size, color, and so on

**Comment by andydotxyz** [comment]
`canvas.Text` already exposes all the font properties, as it is a primitive type. The `widget.Label` however uses the loaded theme, and so will not show the same customisation.

**Comment by t-puetz** [comment]
I understand that, but there are use-cases for where you want to change the font style of a single widget in your app. I am coding a flashcard app at the moment for vocabulary learning and it would be nice if the font of the label I centered inside a rectangle (pitty Fyne does not have a Frame Widget btw.) could be modified (type, size, style etc.). And of course the font of buttons etc should still obey the theme config.

I could use canvas.Text inside the Rectangle instead of the label widget, but then I lose the data binding feature which I really need for core functionality.

**Comment by andydotxyz** [comment]
I don't know what a Frame widget would be, perhaps like the `Card`?
In v2.1.0 we added `RichText` which supports various types of text style like heading etc which may help.
However I think your comments do not relate to this issue where the request was to change the font size of the app.
