### ISSUE TITLE
How can i change the function on the "title bar X"?

### ISSUE THREAD

**Issue by dufuqsls** [fyne-io/fyne#1769]
Hello~
First, i am sorry that my English is not good.

OS : Windows 10 Pro
fyne version :  fyne 1.4.2
programming skill level : newbie

![title1](https://user-images.githubusercontent.com/62934043/104279048-01da5400-54ed-11eb-8441-3cc816bde627.png)

**I want to change function when we click the title bar X button
When we click a X button, some program run a program to go tray menu, not to quit**

base :  When i clicked to "title bar X button", fyne.Quit() execute, i think
After change : Not fyne.Quit(), Window.Hide()

I write a fyne + systray, that is made well
 but When X button clicked, main Programe is Quit

I need to change the glfw source??

**Comment by andydotxyz** [comment]
By default Fyne apps will close when the last window closes.
To avoid this you can ask the window to `Hide` instead of `Close`.

By setting `Window.SetCloseIntercept` you can register a function that will be called instead of automatically closing. In here you should call `Window.Hide()` and the app will keep running.
Just remember that you have a window in the background that should be closed if you want the app to quit normally.

**Comment by dufuqsls** [comment]
**WOW!!!

THANKS A LOT !!!**

thanks for your answering

i solved this problem easily 

a := app.New()
	w := a.NewWindow("")
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.Show()
	a.Run()

**Comment by dufuqsls** [comment]
r
