### ISSUE TITLE
High importance button show no hovered state

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1785]
### Describe the bug:

Hovering over a button is supposed to indicate that it is hovered, but buttons with HighImportance does not show any hovered indication at all. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to the form tab in `fyne_demo`
2. Fill in an email to make the form valid
3. Hover over the dismiss button
4. Hover over submit button and see that it shows no hover

### Screenshots:

![hover](https://user-images.githubusercontent.com/25466657/104480637-1427c100-55c5-11eb-92ca-20605e9ed123.gif)

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.10.5
 - **Go version:** 1.15.6
 - **Fyne version:** 1.4.3 and develop @ f111a10583880fd238c32c7fdcf178f58a0fb41a

**Comment by AlbinoGeek** [comment]
Can this bug be brought into the [2.0.x - bugfixes since binding, storage, animation addition](https://github.com/fyne-io/fyne/milestone/13) milestone?

[or perhaps I misunderstood the naming of that milestone, and it belongs in the other one?]

Ether way, would love to see this in the next version.

**Comment by Jacalz** [comment]
I agree. It is a very noticeable issue. Added it to that milestone for now :)

**Comment by andydotxyz** [comment]
Fixed on `release/v2.0.x`
