### ISSUE TITLE
Tab indents should align correctly

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1791]
In #761 we made a rough approximation.
In full implementation we need to align to the next tab-location  so that "  \tfoo" and "\tfoo" align.

**Comment by adrianre12** [comment]
I have already worked on tabs and have a POC branch working. I have used the simplest way in which I have extended the image/font so that DrafString and MeasureString implement the tabs by moving the dot to the required offset before drawing the next rune.
An alternative would be to split each line into substrings separated by tabs. Each substring would then be drawn separately and added to the canvas at the relative offset.

**Comment by andydotxyz** [comment]
I had not considered the former approach, I assumed we had to do it in the label because the tab could be programatic.
Do you have any feelings on which is faster and/or more flexible?

**Comment by adrianre12** [comment]
Implementing it in DrawString is definitely the fastest, both in coding time and runtime and very easy to back out. I still have to look at how tabs should work with justification, left is easy, the rest ...? Assuming I have not made a huge mistake, I could see that it could be dropped in as a bug fix for 2.0.
The second method is starting to get into the "write a proper editor" realm. I have only just started looking at how the data structures in editors work, but I can see there could be a conflict between how tabs and editor work. e.g. indents and tabs similar but different or calculating cursor position from pointer position.

**Comment by andydotxyz** [comment]
As I understand it tabs need to align to a position to be completed properly - i.e. "1 inch" or "8 spaces".
Somehow this needs to be passed into whatever is doing the rendering.
I don't think we can manage that without new API - meaning it would need to be a minor release not a bugfix.

**Comment by adrianre12** [comment]
Yeup, correct at the moment to prove it works I have it hardcoded at 4 spaces. Which is the same as it is now. I started looking at adding it to the theme under text style but was waiting for approval of the concept before digging into the new theme code.
I am using the width of the space rune to calculate the tab width so that tab-width changes with the font. This is probably the most common understanding of tab i.e. N spaces.

**Comment by andydotxyz** [comment]
That sounds like a good plan

**Comment by andydotxyz** [comment]
This is now landed on `develop` branch
