### ISSUE TITLE
README edit

### ISSUE THREAD

**Issue by kurianCoding** [fyne-io/fyne#186]
`go get fyne-io/fyne`

does not work. you need `go get github.com/fyne-io/fyne`.

**Comment by jadr2ddude** [comment]
I have just confirmed that `go get fyne.io/fyne` works.

**Comment by danopz** [comment]
`fyne.io/fyne` is working, btw is there any reason in not using the normal `github.com/fyne-io/fyne`?

**Comment by yeung66** [comment]
these two both work because the domain `fyne.io/fyne` is pointing to `github.com/fyne-io/fyne`

**Comment by andydotxyz** [comment]
We did not want to tie our project to the github hosting for life - and so we use a "vanity domain".
You should only go get from the fyne.io/fyne path as mixing import paths will cause errors.
Even if you manage to go get from the github location you will probably get errors about using the wrong import path - this should be a more user friendly error than the compile errors that would be triggered otherwise.
