### ISSUE TITLE
AcceptChar/AcceptRune function for widget.Entry

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1925]
### Is your feature request related to a problem? Please describe:
If I have `widget.Entry` that expect for example an integer, then I would like to have a way to tell to the `Entry` to ignore any character (rune) that is not a digit.

### Is it possible to construct a solution with the existing API?
To get this behavior with current API, developers need to extend Entry widget and override TypedRune method. However, I think it is something that Entry should already manage at core level.
A new method would be needed something like (inspired from github.com/rivo/tview):
`SetAcceptChar(acceptFunc func(text string, lastChar rune) bool)` or
`SetAcceptRune(...)`.

### Describe the solution you'd like to see:
Something like this:
```go
e := widget.NewEntry()
e.SetAcceptChar(widget.EntryAcceptInteger)
```
Also, this way will allow the developer to apply other constraints like max length.

**Comment by andydotxyz** [comment]
We should not be exporting such customisations - our approach is to provide the majority useful functionality, and support extending for the less-common use-cases.

This ticket could be either:
1) Request for setting an input as a number only. To do this we need to save that metata, not just allow filtering, because it should impact the keyboard on touchh screen virtual keyboards. This would be a diplicate of #1453.
2) Request for complete customisation of which key strokes should be accepted. This should not be added as parr of the API, it is already supported through extension - see the tutorial at https://developer.fyne.io/tutorial/keypress-on-entry - you simply don't propagate key presses or Runes that you don't want to support.

**Comment by fpabl0** [comment]
> To do this we need to save that metata, not just allow filtering, because it should impact the keyboard on touchh screen virtual keyboards.

Completely agreed.

> This would be a diplicate of #1453.

Oh I didn't see that issue before, sorry. You are right, this is duplicated.

> you simply don't propagate key presses or Runes that you don't want to support.

I am aware of it, that's what I wrote on first comment in this issue too (extend possibility). Maybe I don't explain it clear (the proposal approach was not good), but I was trying to request the same as #1453.
