### ISSUE TITLE
how OnChanged Entry works and make responsive popup

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#2001]
hey dear developers 
can you make func for Entry on_change which when it changes check it or do smth else
and also make only number Entry 
and also for Window on_resize which when resize windows it do smth too 
fyne will be great with these

**Comment by Jacalz** [comment]
Can you please use the issue templates when opening issues? These templates are meant to be used in order to make it easier for us to track and understand the given information. Also, can you please stick to one feature request per issue in the future? I’m sorry to have to bother you with this, but we’ve been though this in the past.

Either way, back to the feature requests. 
1. I don’t think I quite understand what you mean. You can already set/overwrite the OnChanged() function to do whatever you like within the entry.
2. For restricting input types, see: https://github.com/fyne-io/fyne/issues/1453
3. I can’t find any open issue for an OnResize function, but I think I remember taking about this sometime and we concluded that it was not something we would add given that resizing windows is a no-op on mobile.

**Comment by andydotxyz** [comment]
Regarding `OnResized` this is not needed using our layout design.
The window resize event is irrelevant because we expect widgets and containers to manage their own contents. Each of these will be told how much space is available and updated if that ever changes.

This approach reinforces the separation of concerns - the top level layout/container/widget for a window is responsible for allocating space rather than code elsewhere in an app rearranging the contents.

**Comment by madaxemad** [comment]
> Can you please use the issue templates when opening issues? These templates are meant to be used in order to make it easier for us to track and understand the given information. Also, can you please stick to one feature request per issue in the future? I’m sorry to have to bother you with this, but we’ve been though this in the past.
ok :]



> Regarding `OnResized` this is not needed using our layout design.
> The window resize event is irrelevant because we expect widgets and containers to manage their own contents. Each of these will be told how much space is available and updated if that ever changes.
> 
> This approach reinforces the separation of concerns - the top level layout/container/widget for a window is responsible 
for allocating space rather than code elsewhere in an app rearranging the contents.
### for window :
yes layouts great responsive but onresize will have more uses than responsive nevermind
i want to make popup responsive too on onresized and change layout too if it will have enough pixel
can do it with timer check too but it seems joke

### for Entry :
![pic1](https://user-images.githubusercontent.com/77942735/108710953-f20d5100-7529-11eb-8335-08652774fc7b.jpg)

i expected OnChanged(func) instead  OnChanged(String) 'json:""'
please let me know how OnChanged works how to code it what must enter for string and json
thanks

**Comment by Jacalz** [comment]
As for the entry, you’d just set it to any func that takes a string as an argument and doesn’t return anything. For example:
```go
entry := widget.NewEntry()
entry.OnChanged = func(text string) {
    fmt.Println(text)
}
```

**Comment by andydotxyz** [comment]
> i want to make popup responsive too on resize

PopUps and overlays float over the current content and should be temporary. Responsive content should exist at the top level of an application, using layouts as discussed.

> and change layout if window have enough pixel

* Layouts can change dynamically based on size / orientation (see `container.NewAdaptiveGrid`)
* Be sure to remember that none of the fyne coordinate system is measured in pixels (just thought I would mention that in case there was confusion)

**Comment by madaxemad** [comment]
thanks so much
