### ISSUE TITLE
how about use go1.16 embed package to manage  resource files ?

### ISSUE THREAD

**Issue by hongshengjie** [fyne-io/fyne#2008]
as the title discribe

**Comment by andydotxyz** [comment]
We still recommend using `fyne bundle` beacause we support back to Go 1.12.
Additionally doing it this way makes it easier to use the resources :) https://developer.fyne.io/tutorial/bundle.

**Comment by Jacalz** [comment]
You'd do something like this if you were to explicitly use the go:embed support in Go 1.16 and later:
```go
package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon/icon-512.png
var icon []byte

var resourceIcon512Png = &fyne.StaticResource{
	StaticName:    "icon-512.png",
	StaticContent: icon,
}
```

However, as @andydotxyz pointed out, we are mostly using the `fyne bundle` command for bundling data at the moment, due to the backwards compatability. I'll close this for now as I think we have added all the necessary information. Feel free to reopen if that's not the case :slightly_smiling_face:
