### ISSUE TITLE
is there anyway i can close a ShowModalPopup() ?

### ISSUE THREAD

**Issue by jobber2955** [fyne-io/fyne#2089]
i search for github and official website's doc , but i couldn't find anything about this.

i found that , in Fyne 1.0 you can use NewModalPopUp() and then use Hide() to hide it  .  In 2.0 , i found that nothing on the doc but in github , there is something links to "Deprecated" . IDK what does that mean. 
Is it means that in 2.0 ShowModalPopUp() doesn't have a hide/close method or it's hide/close method is deprecated

 OR it means that NewModalPopup() in V1.0 is deprecated ?

is there any way i can close/hide a ShowModalPopUp or is there a similar method to replace this method ?

**Comment by andydotxyz** [comment]
"Deprecated" means that something will be removed in the future - but I think you are looking at old documentation.
Since 2.0 the replacement method `NewModalPopUp` is the way to create a modal, you can use `Show()` to show it and `Hide()` to hide it.

https://developer.fyne.io/api/v2.0/widget/popup.html#func--newmodalpopup

We have cleared out the old deprecated methods in this area so no popup API should be marked as deprecated if you are using the new code.

**Comment by jobber2955** [comment]
> "Deprecated" means that something will be removed in the future - but I think you are looking at old documentation.
> Since 2.0 the replacement method `NewModalPopUp` is the way to create a modal, you can use `Show()` to show it and `Hide()` to hide it.
> 
> https://developer.fyne.io/api/v2.0/widget/popup.html#func--newmodalpopup
> 
> We have cleared out the old deprecated methods in this area so no popup API should be marked as deprecated if you are using the new code.

Thank you for this fast replying , its my fault confound the V1.0 docs and V2.0 docs , all works now , sorry to bother !
