### ISSUE TITLE
Can the Entry control be set to send requests after completion of input?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2090]
When you lose focus, you call the appropriate functions, such as validators, network requests, similar to Ajax, to interact with the server

**Comment by andydotxyz** [comment]
By default all validation etc happens on change.

If you want to add functionality to `Entry` to respond to losing focus you can create a new widget that extends `widget.Entry` and provide a new `FocusLost` method. Remember to call `myEntry.Entry.FocusLost()` so that the original entry still functions.

More info on extending at https://developer.fyne.io/tutorial/extending-widgets.

**Comment by smp12345** [comment]
Can you add this event to the control by default?From the user experience, I believe that many users have such a demand, such as login or registration network authentication, need dynamic verification, rather than wait for all submitted, in the verification

**Comment by andydotxyz** [comment]
I disagree that users expect validation to happen when user exits the widget.
We have designed validation to happen when typing. Matching fields will be ticked right away - and errors will be indicated if the user leaves the input field.

What you are asking for sounds more like delayed validation rather than faster - so I think this is not more desirable than what we already have. It is entirely possible, as described above, but not something we would encourage by putting into the main Entry code.

**Comment by smp12345** [comment]
It's a bit of a delay check, because I can't send a network request until the text field is finished. It's a bit of an AJAX check to see if there's a duplicate user name.You can look at the registration function of the site

**Comment by andydotxyz** [comment]
I think we have answered the question of how this can be done, if you could confirm that it fixed your issue then we can close this :)

**Comment by smp12345** [comment]
Now I can only use Entry OnChange for the time being, which is somewhat different from my expectation. I expect to send network requests after losing the focus

**Comment by smp12345** [comment]
Now I can only use Entry OnChange for the time being, which is somewhat different from my expectation. I expect to send network requests after losing the focus

**Comment by smp12345** [comment]
I have solved my problem through the solution you gave me. But I still suggest adding lost focus support into Entry. I hope you can evaluate it.

Thank you for your help. You can close this issue
