### ISSUE TITLE
Can I create a borderless window? Do not use the title column, how to do?

### ISSUE THREAD

**Issue by 2vl** [fyne-io/fyne#2175]
Can I create a borderless window? Do not use the title column, how to do?

in microsoft windows.

**Comment by andydotxyz** [comment]
There is a desktop extension that can create a splash window, this is borderless.
https://github.com/fyne-io/fyne/blob/a25b08480d742f016ee24c1b37aa02c3bb433bd5/cmd/fyne_demo/tutorials/window.go#L40

We discourage general usage of borderless windows because that is disallowing the user certain functionality that they may rely upon.

**Comment by zyxk** [comment]
This example is a new window. Can a borderless window be used in the main window?
I would like to make a borderless main window, thank you.

**Comment by zyxk** [comment]
Can not use the mouse drag to move the position of an unbounded window, how to set this, I want to be able to use the mouse to move.

**Comment by andydotxyz** [comment]
> Can a borderless window be used in the main window?

Any window could be opened as a splash, it just depends what code you use.

> Can not use the mouse drag to move the position of an unbounded window

Fyne does not support moving, iconifying or maximising windows through code. Splash windows have no user controls, and so cannot be manipulated by the user.

**Comment by Jacalz** [comment]
I think the above question has been resolved. Closing.
