### ISSUE TITLE
how get computer screen size

### ISSUE THREAD

**Issue by ooing** [fyne-io/fyne#2307]
### Is your feature request related to a problem? Please describe:
how get computer screen size

**Comment by andydotxyz** [comment]
We do not expose any screen APIs.
If you expand on what your use-case is we can help further?

**Comment by Gys** [comment]
Maybe this is helpful. It shows the main app window in the middle, covering 80% of the screen area. I use 'github.com/kbinani/screenshot' to get the screen size. 

```
       ...
	a := app.New()
	w := a.NewWindow("MyApp")
       ...
	w.Resize(windowSize(0.8))
	w.CenterOnScreen()
	w.ShowAndRun()
       ...

```

```
func windowSize(part float32) fyne.Size {
	if screenshot.NumActiveDisplays() > 0 {
		// #0 is the main monitor
		bounds := screenshot.GetDisplayBounds(0)
		return fyne.NewSize(float32(bounds.Dx())*part, float32(bounds.Dy())*part)
	}
	return fyne.NewSize(800, 800)
}

```

**Comment by andydotxyz** [comment]
One of the challenges with this is that you're ignoring window scale.
Fyne sizes do not deal with pixels, but device independent sizes. To manually control things like this you need to take into account `Window.Canvas().Scale()`.

Closing because it's not something that is supported - users should be in control of how large windows are and where they are placed.

**Comment by yg7001** [comment]
> One of the challenges with this is that you're ignoring window scale. Fyne sizes do not deal with pixels, but device independent sizes. To manually control things like this you need to take into account `Window.Canvas().Scale()`.
> 
> Closing because it's not something that is supported - users should be in control of how large windows are and where they are placed.

User in charge the running, but programer should in charge when start!

**Comment by andydotxyz** [comment]
Programmers can be in charge of window size using `Window.Resize()`. Calling this should be based on the app content, not the size of a users screen. Anything else is full of assumptions that won't hold universally.

**Comment by lmsenanayake** [comment]
Hi guys, I'm looking for a way to get the device screen size. Is there any way to get it since this last comment ?

> Programmers can be in charge of window size using `Window.Resize()`. Calling this should be based on the app content, not the size of a users screen. Anything else is full of assumptions that won't hold universally.

For me this comment make no sens, because the programmer must be able to know the screen demensions, in my case I would like to have 2 different presentations base on the device's orientation (landscape or portrait)
