### ISSUE TITLE
Supplement data types for data binding code generator

### ISSUE THREAD

**Issue by namezis** [fyne-io/fyne#2361]
This is feature request to improve working with structures and data bound widgets.

Is it possible to supplement the types listed in the code generator **data/binding/gen.go** to other types such int64, int32, float32.

![Selection_731](https://user-images.githubusercontent.com/1754783/128647469-d3e614e7-9c95-4e6a-98e6-df8e18588f30.png)

In many instances one cannot change the structure data type of provided library or code.

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. Thanks for understanding.

As for the actual request here, I’m not entirely sure that it is something that we want to do. These can be implemented by the user through implementing custom bindings. Implementing this would also add a lot of duplicate code and complexity to the data bindings given the lack of generics in Go. I think the current solution of only providing the most used data types is a sensible solution.

**Comment by andydotxyz** [comment]
Yes we did consider this, but did not see a massive upside to the increased overhead.
Mostly we want to have our API focus on the most common use-cases, In most cases up-casting (for example float32 to float64) isn't a big deal because bindings require a certain memory overhead already...
But as @Jacalz says if this worries you it is possible to provide custom bindings.

**Comment by namezis** [comment]
It's OK. I will see how the custom bindings are working...

Sorry for not adhering to the template.
