### ISSUE TITLE
book example image viewer hangs with 20'000 images

### ISSUE THREAD

**Issue by drrob1** [fyne-io/fyne#2370]
### Describe the bug:
Program from chapter 4 of "Building Cross platform GUI applications with Fyne" by Andrew Williams, Packtpub hangs when many pictures are in the directory.  This program is to create a thumbnail of all images in a given directory.  It works when 5 images are in the directory, but hangs on a directory with 20,000 images.  No error messages.  Program does not even show its window.

### To Reproduce:
Directory with many images.  On my computer, this directory has 20,000 images.

### Screenshots:
none

### Device (please complete the following information):
windows 10 PC

**Comment by andydotxyz** [comment]
20`000 images is a lot!
The example in the book is just an example of how it can be done.
A more robust application would probably only create thumbnails for images that are currently visible.

I'm not sure what this bug is against, the book or a toolkit item?

**Comment by drrob1** [comment]
It's against the toolkit, which should fail noisily, or not fail at all, even if I do something stupid w/ it.

**Comment by andydotxyz** [comment]
If you run the software against 20000 images I expect you will see CPU go very high.
I think it is the responsibility of your OS or desktop environment to highlight apps that are doing unwise things.
I don't think a graphical toolkit holds responsibility for showing that your code is hogging a CPU...

**Comment by drrob1** [comment]
That's not what I saw.
After a brief burst of HD activity, I saw nothing unusual.  After about half hour I opened the task manager and it showed that  the example program used 0.1% of resources.  It was easy to end task.
Then I started it and let it run overnight, in case it would recover.  It didn't.  Task manager still showed 0.1% resources and I ended the task.

On a related note, I wrote a different program using fyne.io/fyne/v2, to just show one image but to identify all image files in the directory.  It found all of the files in <10 ms.

**Comment by andydotxyz** [comment]
I have looked into this and the issue appears to be that the app attempts to add 20'000 items into a `Container` using `GridWrapLayout`. Being slow to compute is a limitation of that layout when using massive data. Instead we would recommend an app that wants to support these numbers to use `Table` widget or other collection widget that uses caching to assist with these more complex tasks.

This may seem like a frustrating answer, but the book examples are meant to be illustrative for learning the toolkit, rather than production ready applications.
