### ISSUE TITLE
Canvas Circle disappear after change it's color when light theme is set

### ISSUE THREAD

**Issue by tandem97** [fyne-io/fyne#2467]
### To Reproduce:
Steps to reproduce the behaviour:
Run this code with light and dark theme

### Example code:
```go
package main

import (
	"image/color"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/theme"
)

func main() {
	app := app.New()

	mainWindow := app.NewWindow("Hello")
	mainWindow.CenterOnScreen()
	mainWindow.Resize(fyne.NewSize(800, 400))
	mainWindow.SetIcon(theme.FyneLogo())

	//app.Settings().SetTheme(theme.DarkTheme())
	app.Settings().SetTheme(theme.LightTheme())

	test := canvas.NewCircle(color.Black)

	mainWindow.SetContent(test)

	go func() {
		time.Sleep(time.Second * 3)
		test.FillColor = color.RGBA{38, 194, 129, 1}
		test.Refresh()
	}()
	mainWindow.ShowAndRun()
}
```
-->

### Device (please complete the following information):
- win 10
 - go 1.17
 - fyne 2.1 rc1

**Comment by andydotxyz** [comment]
This is correct, you are changing to an alpha value of `1`, which is around 0.3% opaque (maybe you meant 255).
The reason you see different behaviour in light and dark theme is because your colour is not what you think it is - `RGBA` should be pre-multiplied colours, so your R, G, B channels are all out of bounds. Try using `NRGBA` instead, which allows regular RGBA channels without needing to be multiplied. This is a constraints of the Go `color` API.
