### ISSUE TITLE
Structured and stateful themes for widgets to allow different styles for same widget type

### ISSUE THREAD

**Issue by kravemir** [fyne-io/fyne#255]
Currently, fyne uses flat global theme for whole application defined by:

```
type Theme interface {
    BackgroundColor() color.Color
    ButtonColor() color.Color
    HyperlinkColor() color.Color
    TextColor() color.Color
    PlaceHolderColor() color.Color
    PrimaryColor() color.Color
    FocusColor() color.Color
    ScrollBarColor() color.Color

    TextSize() int
    TextFont() Resource
    TextBoldFont() Resource
    TextItalicFont() Resource
    TextBoldItalicFont() Resource
    TextMonospaceFont() Resource

    Padding() int
    IconInlineSize() int
    ScrollBarSize() int
}
```

The goal is to allow visual separation of different application parts and components. Use-cases:

* custom styling for sidebar components,
* different styling of different message components/variants (blue info, yellow warning, red error, green advice, gray neutral,...),
* different styling of buttons according to specific application design (primary button, destructive button, secondary button, subtle button,...),
* different styling of required and non-compulsory fields and their labels,
* and more,...

So, in order to achieve that, I propose individual styles assignable to widgets:

```
type StyleDefinition interface {
    BackgroundColor() color.Color
    TextColor() color.Color

    TextSize() int
    TextFont() Resource

    Padding() int
}
```

However, widgets can have different states, so in the end, a widget is to be assigned a more complex style:

```
type WidgetStyleDefinition {
    styles map[string]StyleDefinition
}
```
However, a single widget can be in multiple "orthogonal state modifiers". So, state representation would be `string` containing space separated list of individual active state (modifiers).

For example button states can be: `""`, `"hover"`, `"pressed"`, `"disabled"`, `"disabled hover"`, `"hover pressed"`,... And, input states can be `""`, `"empty"` (placeholder shown), `"hover"`, `"selected"`, `"hover selected"`,...

**Comment by kravemir** [comment]
Continuing design proposal, a `Theme` would change to:

```
type Theme interface {
    widgetStyle(name string, class string) StyleDefinition
}
```

Where `widgetStyle(name string, class string) StyleDefinition` would return specific style for a widget with name (`button`,...) and `class` (`nil`,`primary`, `secondary`,...).

**Comment by andydotxyz** [comment]
Thanks for your proposal. There is a lot in here but I will do my best to respond so we can shape this to fit the Fyne ambitions. Part of our design is to promote application consistency - a user experience that cannot be trivially compromised by "this label is larger" or "this dropdown is transparent". The current theme definition has a long way to go, but it is designed to allow applications the flexibility to customise for their brand but not to deviate from the design principles. Your note about "required" input or "primary" button are intended to be part of the design already.

If we were to explore the theme capabilities per-widget we would need to find a way to do it using a typed API rather than string parameters. Some of the proposal above is quite "web" (like class names, coloured boxes) and I think that users native applications have different expectations (part of the reason why I have not worked in the direction of hybrid apps or embedding HTML content. We need to make sure that any Fyne APIs are clear, easy to use and can be auto-completed by any IDE. 

Another consideration (which I think your proposal accomplishes) is that a widget style should be separate from it's logic. Looking at your description above I think it goes in the opposite direction - a theme must know about every widget, so if we add a new widget is added then every theme written will need to be extended - I want to avoid this as the EFL widgets all fell into this hole. The current theme capabilities allow the creation of widgets that match the loaded theme without having to extend it - until the time that we add a new theme primitive, such as shadow or disabled text.

I hope this all makes sense. Perhaps you can see how this fits with your proposal and revise it to suit?

**Comment by kravemir** [comment]
@andydotxyz thank you for the answer and thinking about topic :-) 

> Part of our design is to promote application consistency - a user experience that cannot be trivially compromised by "this label is larger" or "this dropdown is transparent". 

Sometimes, I see people to confuse consistency with sameness. However, consistency itself means nothing specific in software, as it's merely aspect of some measurement result, or way of treatment.

For example, in spacing and sizing context. There have been studies about vertical rhythm and impact on UX, which proved that sameness of rhythm just made things worse to get oriented in.

Use same line spacing for text paragraphs, but use different spacing between paragraphs, and use different spacing between texts and rest of the page (or software like some application shops containing description).

Use same spacing within forms between controls, but use bigger spacing between forms and rest of the page / application. Or, wrap it in "boxes" (not common in material design) and use same form margin.

Consistency in sizing context means to use same spacing/sizing for same things, but things can be different. Different application have got different structuring, and need different sizing patterns. Some application are more complex, and need lots of base sizes. Some applications are simple, and need only few base sizes.

> Your note about "required" input or "primary" button are intended to be part of the design already.

Please, show me what you mean by "required" input being part of design. I have missed that in docs.

> Some of the proposal above is quite "web" (like class names, coloured boxes) and I think that users native applications have different expectations (part of the reason why I have not worked in the direction of hybrid apps or embedding HTML content. We need to make sure that any Fyne APIs are clear, easy to use and can be auto-completed by any IDE.

Agree, that web pages and applications, are different things, and there are different expectations. But, almost the same UX principles apply for both native and single-page web applications (not pages).

However, different UX principles apply for mobile (handheld touch) applications and desktop (keyboard + mouse) applications. Mobile applications and desktop applications need different structuring, and therefore different spacing patterns. Each of it is consistent, but with different pattern in mind. Therefore, not sameness also applies here.

> Another consideration (which I think your proposal accomplishes) is that a widget style should be separate from it's logic. Looking at your description above I think it goes in the opposite direction - a theme must know about every widget, so if we add a new widget is added then every theme written will need to be extended...

No. The same issue applies also to current theme architecture. Difference is, that it has been put into flat structure.

> If we were to explore the theme capabilities per-widget we would need to find a way to do it using a typed API rather than string parameters. 

Yes. This is a the most tricky part, which needs much more thinking, than coding :-)

Looking at theme:

![image](https://user-images.githubusercontent.com/1643935/57583171-24bd9500-74ce-11e9-972b-cbee585b9993.png)

Some of UI designs had following requirements (don't remember precise colors and values now):

- dialog window intro text with font size 11px, color #444,
- form label font size 11px, color #555,
- input value font size 12px, color #333,
- input field border 1px, color #999,
- field hint text (right of field) with font size 10px, color #777,
- button label font size 11px.

Is it possible to achieve that with fyne, or does fyne goes in direction, which allows that?

**Comment by kravemir** [comment]
> a user experience that cannot be trivially compromised by "this label is larger" or "this dropdown is transparent".

I would like to add, that I perfectly agree with this. However, this a aspect, which can't be truly enforced by library/framework, and at same time allow library to be reusable as general application GUI framework/library. 

It depends on correct development of each software, which needs to:

* define fine set of styles for the application, based on UI design guidelines:
   * for example complex application: 7 variants of buttons, 4 variants of boxes with different paddings and children spacings, 2 variants of labels, 2 variants of inputs, 12 variants of texts,..
   * for example simple application: 2 variants of buttons, 2 variants of boxes with different paddings and children spacings,  1 variant of labels, 1 variant of input, 3 variants of texts,..
* use prepared UI styles, and stick to them,.. don't invent a new style with a new component.

So, that's aspect left to users. If you want to protect them to shoot themselves into foot, then you can't truly do that, unless you take a gun away from them, but then you will leave them vulnerable against bears and wolves,..

**Comment by andydotxyz** [comment]
> Sometimes, I see people to confuse consistency with sameness. However, consistency itself means nothing specific in software, as it's merely aspect of some measurement result, or way of treatment.

I don't disagree with this - but I don't think it invalidates the use of "consistency" as the concept is still what we are striving for.

> Please, show me what you mean by "required" input being part of design. I have missed that in docs.

It's not in yet, but it is supported by the current approach as far as I can see.

> However, different UX principles apply for mobile (handheld touch) applications and desktop (keyboard + mouse) applications.

I agree about this as well - the current plan is that widgets would encode the flow or layout differences. As far as I can see the theme does not impact the sorts of UX changes that apply across different platforms. As with the rest of the API our intention is that a theme would apply across mobile and desktop equally.

> No. The same issue applies also to current theme architecture. Difference is, that it has been put into flat structure.

I don't follow this - the themes have no widget definition in them at all (by design). We can add new widgets without extending themes. If the widget style is encoded in the theme this is no longer the case.

Following your theme illustration above and your "Is it possible to achieve that with fyne" - the answer is some yes, some no. The biggest no is that we don't have a different font for each widget. The input field could have a border but the widget has chosen the underline rather than a border (you can see older versions where we had a border).

I hope that all helps.

**Comment by andydotxyz** [comment]
> I would like to add, that I perfectly agree with this. However, this a aspect, which can't be truly enforced by library/framework, and at same time allow library to be reusable as general application GUI framework/library.

Fyne's approach to this is that widgets have a set style (that can be themed) but the canvas remains fully available to do whatever specific designs a developer chooses to code.

**Comment by kravemir** [comment]
> I don't disagree with this - but I don't think it invalidates the use of "consistency" as the concept is still what we are striving for.

You're right, it does not invalidate consistency. However, it takes "consistency" to a level beyond just consistency, as it incorporates "sameness of styling mechanism" into GUI framework. Therefore, individual applications can tweak colors, fonts, and some attributes. But, they cannot set their own styling mechanism.

This "sameness-of-styling-mechanism level of consistency" is maybe suitable for small and simple applications. However, usually real world applications for end-users need more complex styling mechanism, as I've explained above.

> Following your theme illustration above and your "Is it possible to achieve that with fyne" - the answer is some yes, some no. The biggest no is that we don't have a different font for each widget. The input field could have a border but the widget has chosen the underline rather than a border (you can see older versions where we had a border).
>
> I hope that all helps.

Honestly, it does not help. Anyway, thank you for explanation and description of fyne's goals. 

I was picking a GUI framework for Go to learn. Well, it seems, that I, and my expectations and needs, don't fit into fyne's target user base.

**Comment by damiantoczek** [comment]
I think you confuse consistency with good user experience, it's not the same. If something is too similar it will cause a bad user experience, I'm not saying that the default one is bad and I actually like it. But developers should be able to align things in a specific way and maybe remove borders, add them, do some "on hover" effects, etc.
I want to create an app for a game and if everything is "consistent" then it won't be a good experience, because everything will look too similar and it would probably require some sort of section labels so people know what is what. It could also be done with a different style or alignment so people know "ok those are the main characters and this at the bottom are the subclasses of characters" but instead you need to write it all down. Because of how limiting the styling is I'm worried that when I start doing my project I will come at a point where I won't be able to continue because something won't be possible to achieve. By that I talking about dropdown menus with images, cards that can be for example drag and dropped, etc. The default style is good but I want to be able to do some adjustments. I don't want to convert the default style into art but I want some control.

**Comment by andydotxyz** [comment]
>  Because of how limiting the styling is I'm worried that when I start doing my project I will come at a point where I won't be able to continue because something won't be possible to achieve.

I think you would need to be more specific about what it is you need that is not currently possible.

> dropdown menus with images

There is an open PR for this already

> cards that can be for example drag and dropped

Anything can be drag and dropped if the code is added, we don't have that in the core toolkit yet though... where would it be added?

> I don't want to convert the default style into art but I want some control.

Absolutely, we want to provide control where we can represent the it as some sort of user intent (we want all interaction to have visual hints). So let's get into the details of what cannot be done with new feature requests?
