### ISSUE TITLE
Incorrect (initial) minSize for images with FillMode canvas.ImageFillOriginal

### ISSUE THREAD

**Issue by toejough** [fyne-io/fyne#259]
with OSX Mojave, the following code produces the desired image on load, and then just a blank window on any resize event:

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	// "fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("photo")

	image := &canvas.Image{
		File:     "/path/to/photo.jpg", // file path to image
		FillMode: canvas.ImageFillOriginal,      // constrains aspect ratio
	}
	image.SetMinSize(fyne.Size{Width: 500, Height: 500}) // by default will be 0, 0 :-/

	view := widget.NewHBox(image)

	w.SetContent(view)
	// w.Canvas().SetOnTypedKey(func (keyEvent *fyne.KeyEvent) {
	// 	print("refreshing")
	// 	// w.SetContent(view)
	// 	// w.Canvas().Refresh(w.Content())
	// })
	w.ShowAndRun()
}
```

Other behaviors:
* if the content is set to the image directly, resizing works awesomely: the image resizes to fit the room available, and any extra room outside its original dimensions is evenly filled with empty buffer space.
* if resetting the content on typed keys, the window blows up to be the full resolution of the underlying image when typing a key
* if refreshing the window canvas on typed keys, nothing obvious happens to the window

Perfectly happy to have someone tell me I'm doing it wrong, but I've spent a fair amount of time reading other people's code and the official docs and experimenting, and I haven't figured out how to get the image-as-content behavior when using the widget (I want the widget because I want to add more to my app than just a single image).

**Comment by andydotxyz** [comment]
The main reason you are seeing undesirable behaviour is because the canvas.Image has no standard minimum size, and most layouts are packed at minimum size. The widget.HBox will use the minimum width to pack items, hence not seeing the image as it's minSize by default is 0, 0.
Calling image.SetMinSize() is the right thing to do when loading an unknown image content, so the example should work.

When you want to refresh an object don't set the window content, call canvas.Refresh(myObject).

What size is your original image? I think that canvas.ImageFillOriginal may not be what you want but instead canvas.ImageFillContain - that will maintain aspect ratio whilst displaying the whole image in the available space.

It appears that you have found a bug in that the image displaying at full size when set to canvas.ImageFillOriginal is incorrect - on initial draw it seems to ignore the image dimensions.

I think that the "other behaviours" you list are as a result of the bug identified and also that you are requesting "FillOriginal" which will do everything it can to expand and display your image at it's intended resolution - not normally the desired outcome.

**Comment by andydotxyz** [comment]
I have changed the title of this as I think the real bug is the initial MinSize of the canvas.ImageFillOriginal images. I cannot replicate item 2 or 3 of "other behaviours" which I think is because I am using a smaller image which works OK with the original fill sizing. If your image is huge you may find strange behaviour if you ask the window to expand to this level.

If we resolve the bug now in the title then your image.SetMinSize() would not be needed and you should have a reliable experience.

**Comment by toejough** [comment]
Hmm, yeah, my image is pretty large.  I'll give the `ImageFillContain` a try tonight & let you know what happens - thanks for the swift response!

**Comment by toejough** [comment]
`ImageFillContain` does indeed show my picture through resizes.  Thank you!

In the `HBox` it doesn't scale like I want, but I'm guessing I'll have to implement a custom widget or a custom layout to use with `NewContainerWithLayout` to get that - I'd like the other components to scale to minSize, but have the image scale up to fill up whatever is left in the window.

**Comment by andydotxyz** [comment]
You probably should check out BorderLayout - that is most likely what you want - the top, bottom, left and right items are packed in and any other items fill the remaining space in the middle.

You can see the different layouts in action in fyne_demo - and also documented by a recent blog post at https://www.lucasepe.it/posts/golang-desktop-ui-fyne-layouts/

**Comment by toejough** [comment]
ah - I wasn't thinking about the borderLayout because I didn't need _all_ the borders, but that's an imaginative failure on my part - thank you!  

Generally, I've got to say, this is an awesome project. You've been very responsive, the API is concise, the UI is (so far in my limited use!) very responsive even on my older laptop.  As my go skills improve, I hope to be able to contribute back!

**Comment by andydotxyz** [comment]
This is now resolved on develop ready for testing.
It was much easier with the various minSize fixes that have gone into this release :)
