### ISSUE TITLE
FormLayout is misaligned

### ISSUE THREAD

**Issue by etolnz** [fyne-io/fyne#2605]
Using: Windows 10 Home 
go version go1.17.2 windows/amd64
fyne 2.1.1

I used this example for Form Layout (The only thing I changed was "color.White" to "color.Black).

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Form Layout")

	label1 := canvas.NewText("Label 1", color.Black)
	value1 := canvas.NewText("Value", color.White)
	label2 := canvas.NewText("Label 2", color.Black)
	value2 := canvas.NewText("Something", color.White)
	grid := container.New(layout.NewFormLayout(), label1, value1, label2, value2)
	myWindow.SetContent(grid)
	myWindow.ShowAndRun()
}
```
The two columns do not line up

![FormLayout](https://user-images.githubusercontent.com/70080372/139760039-6f8a9110-9c19-48fd-86a4-0621b60837a5.PNG)

I do not understand why.

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

It’s fin for this case given that you have included pretty much all of the relevant information. I’ll just format your code to put it inside a code block so it’s more readable.

**Comment by andydotxyz** [comment]
The reason here is that `canvas` package elements do not understand standard layouts and padding. If you used `widget.Label` instead then it would work as expected. The elements in canvas package are intended as low level drawing primitives so be careful when you mix them in with widgets, as you may need to do some extra work to, for example, align. 
You can see more about standard widget alignment at https://developer.fyne.io/architecture/widgets

**Comment by etolnz** [comment]
Thank you.  That takes care of it.
