### ISSUE TITLE
Detecting if the bottom of a widget Table has been reached 

### ISSUE THREAD

**Issue by alainmedale** [fyne-io/fyne#2683]
### Is your feature request related to a problem? Please describe:
I am trying to build an app that displays images as widget Table using fyne. And it is really important in this case to be able to detect if the bottom of the Table has been reached, so that the app can add even more images.

### Is it possible to construct a solution with the existing API?
 The Table widget has scroller API in it but just not exposed yet.

### Describe the solution you'd like to see:
table.BottomReached() bool

**Comment by andydotxyz** [comment]
I don't think this can be a field because it's more likely that you want an event rather than a flag.

It is not exactly the bottom, but it might give a better experience if the user is "nearly at the bottom" to load more.
This can currently be done :) If you check `if cellID.Row == len(myData) - 1 && cellID.Column == 0 { loadMore() }`.
Because our Table will call your row callback when an item is about to be displayed this will fire at around the right time.
We check the column is 0 so that it is only called once. If you offer horizontal scrolling you may need a little smarter logic as it may not be loading col 0 as the user scrolls.

**Comment by alainmedale** [comment]
Thank you for the detailed answer provided. The solution that you proposed works. 

Thanks again

**Comment by andydotxyz** [comment]
Glad you're sorted
