### ISSUE TITLE
Get data from tableItems.

### ISSUE THREAD

**Issue by jiangdon** [fyne-io/fyne#2801]
### Is your feature request related to a problem? Please describe:

I'm using a table control to display my data and I want to save the processed data, but I can't find how to get the data contained in tableItems. Is there a related function in the current version that can achieve this?

### Describe the solution you'd like to see:

![111](https://user-images.githubusercontent.com/31313969/155090380-5d83b396-5e96-46ad-a3ab-85845d266760.png)
I want save those data from tableItems. Do you have plans to implement this feature?

**Comment by Jacalz** [comment]
I haven’t used table much honestly but I don’t think there is anything that needs to be added to support this. It should already be doable.

You would just have to hook up the fields in your UpdateItem() function to add the contents in the widgets to your underlying data source (the one that ideally control the table size). If you use a 2d-slice for the table data, you can take the indexes that you get in the UpdateItem function and use that to grab the data from the widget at that position and put it inside your data slice.

I don’t think I have any good example for this but it is relatively similar to how I use the list widget in this example (instead of setting data for the widgets, you’d of course get the data form then instead): https://github.com/Jacalz/wormhole-gui/blob/5a9382e7776f7c53b633b950fcabc64f7c1c4c22/internal/transport/bridge/recv.go#L40

**Comment by andydotxyz** [comment]
> but I can't find how to get the data contained in tableItems

With the table widget your code controls the data. Therefore you already have the full data in your app somewhere...

**Comment by andydotxyz** [comment]
Closing as not an issue as described above - we do not have plans to add APIs that give you access to data that you control.
Feel free to re-open if you think that I misunderstood.

**Comment by jiangdon** [comment]
yes, thank you.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fyne-io/fyne"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fyne-io/fyne] Get data from tableItems. (Issue #2801)





 
Closing as not an issue as described above - we do not have plans to add APIs that give you access to data that you control.
 Feel free to re-open if you think that I misunderstood.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
