### ISSUE TITLE
Memory leak on NewMultiLineEntry text refreshing

### ISSUE THREAD

**Issue by hehpollon** [fyne-io/fyne#2872]
### Describe the bug:
Memory leak on widget.NewMultiLineEntry() text refreshing.

### To Reproduce:
Example code below.

### Screenshots:
![스크린샷 2022-03-27 오후 8 08 33](https://user-images.githubusercontent.com/4995030/160278704-6e2b75c3-e755-4e72-8b7e-b98dead2411a.png)

### Example code:
```
textArea := widget.NewMultiLineEntry()
....
// call multiple times with string msg
textArea.Text = msg
textArea.Refresh()
textArea.DragEnd()
```

### Device:
OS: Windows, MacOS
Version: 10
Go version: 1.17.7 windows/amd64
Fyne version: 2.1.2

**Comment by andydotxyz** [comment]
Yes, I think this relates to the general concept of caches growing because we rasterise all the vector elements (text included) for faster drawing. Each minute (or 5? I cannot recall) the content should be marked as dirty if it has not been used since last cache clean.
So try what you have replicated, leave it for a bit, then come back. The second time it should re-use memory that was already allocated.

I don't think we can help growing in memory usage a little over (short) time. The question is, is this really problematic?

**Comment by andydotxyz** [comment]
If the above description does not hold then you may have found another issue and help to track it down would be appreciated :)

**Comment by appl3s** [comment]
I may have encountered the same bug, in my case, I need to use Entry to simulate a logview, after setting Text and refreshing every time in seconds, the memory grows at a speed of about 100MB, and even reaches 6GB of memory usage Rate.

**Comment by appl3s** [comment]
pprof said `20720.70MB 29.13% 71.40% 20755.28MB 29.18%  fyne.io/fyne/v2/widget.(*textRenderer).Refresh`
