### ISSUE TITLE
onDropFilesEvent

### ISSUE THREAD

**Issue by 1207702931** [fyne-io/fyne#2903]
Is there any such function like 
[](https://github.com/lxn/walk)
![image](https://user-images.githubusercontent.com/49967413/162559944-59f0e40b-05b0-4675-b3b4-5159ae30e279.png)

**Comment by Jacalz** [comment]
No, not currently unfortunately. Drag and drop support is targeted for a future release but it has taken sone time because it is a complicated topic. We need to get it right across multiple operating systems. I’ll close this in favour of  https://github.com/fyne-io/fyne/issues/142 that tracks the feature in question.
