### ISSUE TITLE
Move dialog windows to modal popover

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#294]
Should we do this?
It's a cross platform way to disable the underlying content which seems desirable.
But would potentially mean the window needs to expand to fit the dialog content, which may not be expected.

Thoughts?

**Comment by okratitan** [comment]
Well... you could always have a modal popover that uses scroller when it's contents would exceed the window size.  This would prevent window expanding.

I prefer popovers to dialog windows - but I get a feeling that many will want dialog windows instead of popovers.

Perhaps we add a couple utility functions to dialog that allows the user to construct a dialog either using a window or modal popover. Their choice.  Shouldn't add much code as all the underlying children of the window/popover would obviously be the same and so it would use the same code.

**Comment by andydotxyz** [comment]
I appreciate we could support both but as a toolkit I feel that we should be decisive and choose one or the other.

**Comment by andydotxyz** [comment]
This is in PR #303 for comment. Does anyone want to test / feedback before merge?

**Comment by andydotxyz** [comment]
This is now on develop for testing
