### ISSUE TITLE
I think Fyne lacks a lot of customizable options at present. It is too standardized

### ISSUE THREAD

**Issue by Seikaijyu** [fyne-io/fyne#3053]

**Comment by Bluebugs** [comment]
It seems you might have a lot of idea on what you would like to see made more customizable. The current form of this issue, doesn't really allow us to address anything as we do not know what you have in mind. Also we do prefer to track things in item that represent an individual bug fix/feature/improvement.

I think that if you want your issues to get a chance to be addressed, it would be best to open dedicated issues that will describe what each improvement or new feature you have in mind would be. This way we can discuss how this could fit in Fyne and work on them.

**Comment by SuperLiveYou** [comment]
Thank you for your answer. I think Fyne can imitate the web and customize a set of attributes for each component to facilitate customization of personalized components

**Comment by Bluebugs** [comment]
QML is implemented by using canvas object and its language allow manipulation of such object. You could do probably the same by using Fyne Canvas object directly and providing it in a container where you layout function is basically the scripting logic. The history of QML has shown that the scripting logic you use is going to be a performance killer and that you want something fast and that is not called very often (so all the heavy work is done outside of the scripting language). Maybe this day using webassembly there make sense. No idea, just a suggestion.

CSS is, I think, impossible to do outside of the web as the standard has grown extremely big and tied to it. I would think that project like GTK have shown how hard it is to do and that you never really leverage the ability of the Web by doing so.

I can see the use case for a technology of something like QML (I have worked on precursor of this technology) especially for custom interface where it might make sense. Still I think this is out of scope for Fyne itself as it will lead to a more complex API (You now have to learn two language one for Fyne and the FyneML you will come up with) and it won't match material design anymore due to its flexibility. So I don't think it should be integrated in Fyne itself, but you should be able to develop such a component outside of upstream Fyne repository.

**Comment by SuperLiveYou** [comment]
Yes, I also think that embedding in Fyne source code is unreasonable and will reduce performance, so I plan to implement the compiler and enable it to generate go code, just as the XAML file of WPF does (although XAML is still compiled into bytecode and executed, it will generate a partial class that provides an interface for the C sharp file

**Comment by SuperLiveYou** [comment]
According to your answer just now, Fyne will not have better support for custom components in the future, right? Or did I get it wrong?

**Comment by SuperLiveYou** [comment]
Fyne is designed to be simple, easy to use and non customized, right?

**Comment by SuperLiveYou** [comment]
OK, thank you for your answer
