### ISSUE TITLE
how i can build my resource

### ISSUE THREAD

**Issue by mohamadpk** [fyne-io/fyne#3078]
### Describe the bug:
i compile demo app
then i try to change demo app assets 
i try this code 
`go run D:\Important\GO-PATH\src\fyne.io\fyne\v2\fyne bundle -package data -o bundled.go assets `
response in cmd is 
`package command-line-arguments is not a main package`
then i try to compile and install fyne as a exe 
`D:\Important\GO-PATH\src\fyne.io\fyne\v2>go build`
response in cmd is nothing
then i set -o fyne.exe to build
fyne.exe created but is not exe is a lib file

how i build my assets???

**Comment by Jacalz** [comment]
If you want to re-bundle the bundled file for `fyne_demo` you should not need to do anything more than run `go generate` in the `cmd/fyne_demo/data` folder.

It seems to me like you are using the wrong path to the `fyne` command. You should build and install the command using `go install fyne.io/fyne/v2/cmd/fyne@latest` instead of trying to build the library. Once the command is installed, you should just be able to run the command without specifying the path.

**Comment by mohamadpk** [comment]
tnx this work 
`go install fyne.io/fyne/v2/cmd/fyne@latest`

**Comment by Jacalz** [comment]
Great. I’ll close this then.

**Comment by andydotxyz** [comment]
You could also have accessed it directly, but you would need to go to the `cmd` subdirectory:

`go run D:\Important\GO-PATH\src\fyne.io\fyne\v2\fyne\cmd\fyne`
