### ISSUE TITLE
Add text wrap support to widget.textProvider

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#332]
Allow wrap to be turned on for widget.Label and widget.Entry.

Required for #149

**Comment by andydotxyz** [comment]
This would wrap on current widget width, taking the longest line for each that does not extend beyond this width. Proposed API leaves default behaviour unchanged and adds the following:

WrapMode fyne.TextWrapMode [NoWrap, Truncate, WordWrap]
WrapLineLimit int [0 (default) is unlimited]

If WrapMode is set to Truncate then the label will be a single line but not stretch to fit the string
If WodeWrap is set then it will create as many lines as required, up to the limit, if set.

**Comment by stuartmscott** [comment]
Hey all,

This is a highly desired feature for a project I'm working on, but there doesn't seem to be a lot of traction here. I started working on this based on the initial work by @AliceCyber but have run into a few issues;
 - The cursor and selection positions are in "view" space rather than "model" space causing some weird behaviour such as; if the wrap mode is set to truncate, SelectAll only selects visible text, not the whole buffer.
 - Entry has a multiline flag and it is unclear what text wrapping should do if this is set false.
 - Scrollers introduce another level of complexity and I couldn't follow how it decides to layout and resize its content.

See the current work on this branch: https://github.com/stuartmscott/fyne/commits/wrapping

I'm new to the Fyne project so I'd like some clarification on the best approach before continuing

**Comment by andydotxyz** [comment]
Thanks for the input. I think we realised that the proposed approach in that PR has limitations that meant it probably wouldn’t work.

I don’t follow that “select all” should select text that is clipped by an ellipsis, isn’t selecting what is on screen the right thing to do?

I think you’re right to call out non-multiline entry as a special case - within entry it’s probably going to disable word wrap for that reason.

Scrollers should not make this more complicated if wrap is enabled it would just scroll vertical, and if it’s off then it will scroll as before - it should “just work”.

I’d recommend working from the proposed API I posted above rather than the character based wrapping in the PR. If you’d like to chat more you can join us on gophers Slack server :)

**Comment by stuartmscott** [comment]
Hey Andy, thanks for your response. Just to be clear the issues I mentioned above were encountered in my own branch. I've created #712 from it so we have a place to discuss, but note that at this time is NOT ready to merge.

I guess it comes down to our mental model of wrapping and truncation.  I see wrapping as "soft" in that it doesn't actually insert newline characters but displays the text as though there was a '\n' there. Truncation is also "soft" in the sense that it is not destructive - the superfluous text is not deleted, it is just not shown for brevity. Suppose there was some text "Hello Wo..." and you wanted to "Select All" + "Copy", would you expect your clipboard to contain "Hello Wo..." or the full "Hello World"? I would expect the latter, and if I wanted the former I could just select it directly. I think "Select All" should mean "select everything in the model" not just "select what is on the screen".

It makes sense to only allow TextWrapOn if Entry.multiline. I think it should allow TextTruncate so the developer has the choice of letting the widget expand to fit the text with TextWrapOff (default) or truncate the text to fit the widget width.

The current behaviour (TextWrapOff) is that the scroller will let the content expand indefinitely adding a horizontal scrollbar. With TextTruncate content wider than the scroller width should be truncated - no horizontal scroll. Similarly with TextWrapOn content wider than the scroller width should be wrapped to the next line - no horizontal scroll.

#712 is an implementation of the API you proposed above albeit with one difference; rather than explicitly setting WrapLineLimit it uses the widget.Size().Width.

**Comment by andydotxyz** [comment]
Thanks so much, I have commented at the PR regarding the code, I will try to respond to the other questions here.
I agree that wrapping is "soft" - newlines should certainly not be inserted. I guess you are right that the copy should get all the text. I think that this can be done with the current code though, the presentation of the selection is not tied to the text it selects, appropriate changes should allow what you describe.

As you say entry is special and we can only allow wrap if it's multiline. I don't know if I agree that entries should allow truncate though - how can the user edit something if they cannot see it? - this may be better addressed by adding scrolling to entries as hinted at #471 .

I agree with your summary of scroll characteristics, but I don't know how we can easily do it if the scroller is a parent of the text item - it would probably require some special code in scroller. I'm wondering if perhaps we discourage having text in scrollers with wrap/truncate set, as they are different approaches to overflow (in fact such an assertion probably eases entry issues?).

As mentioned on the PR WrapLineLimit was intended to limit the number of rows, not the length of them - perhaps the name isn't ideal?

**Comment by stuartmscott** [comment]
Agreed that Entry should only wrap if multiline and should never truncate, but since wrapping occurs in textProvider what do you think the best way to enforce this would be?

I don't think adding scrolling to Entry is the right way to go since there is already a component to handle scrolling it doesn't make sense to duplicate this functionality. I would prefer to tell Scroller to only scroll vertically, and not horizontally. That way the text can be as big as it need vertically (perhaps limited by WrapMaxLines as mentioned before), but horizontal behaviour is determined by the wrapping mode;
- TextWrapOff expands the widget as before (default).
- TextWrapTruncate hides text longer than width (only applicable to Label and Hyperlink).
- TextWrapBreak and TextWrapWord wraps content onto the next line.

**Comment by andydotxyz** [comment]
I guess that textProvider could require a new function "canTruncate"? 

You might be right about asking scroll to be just vertical - that has been requested before. However I have this niggling feeling that people might expect an entry to scroll. Then I also worry - can we implement "keep cursor visible" inside an entry that is embedded in a scrollcontainer? (Sorry, just a random thought)

Your illustration of how it could work all makes sense, thanks - it makes sense to go ahead with this plan because even if scroller becomes integral the same code will be required.

**Comment by stuartmscott** [comment]
Okay, now Entry does not allow TextTruncate so falls back to TextWrapOff, similarly SingleLine Entry does not allow TextWrapBreak/Word so falls back to TextWrapOff.

I think the way to go here is that Scroller by default scrolls H & V, with options to restrict to just H or V as it covers most use cases;
- By default Entry does not scroll and will grow to fit the text.
- If you want an Entry to scroll, add it to a Scroller.
- If you want an Entry to only scroll H, add it to a Scroller that only scrolls H. If multiline it will grow taller to fit all the lines.
- If you want an Entry to only scroll V, set it to MultiLine, add it to a Scroller that only scrolls V, and it will grow wider to fit the longest line.
- If you want an Entry to only scroll V and wrap, set it to MultiLine with TextWrapBreak/Word, add it to a Scroller that only scrolls V. Note: need to think about how to implement MinSize in this case.

"Keep cursor visible" is definitely a good random thought - although I would implement it a bit more generically - give Scroller "ScrollTo(x, y int)". The Entry can already convert the cursor position into row,col and since it knows the height of each row, and can measure the length of a substring it can figure out the exact x,y coords. Then (and here's the tricky bit) whenever the cursor moves it tells its parent to make sure that coordinate is visible, if the parent is a Scroller it will interpret this as ScrollTo(x,y). I can see this API being useful in testing too.

Coming back "WrapMaxLines" I think there is a better way of doing this. Right now Entry has "MultiLine bool", instead this could be "MaxLines int" with a default of 1 preserving the current SingleLine default behaviour. Setting Entry to MultiLine means "MaxLines = 0 or -1" ie "no limit". Setting Entry to only showing 3 line preview mean "MaxLines = 3". The same field can be added to Label and Hyperlink too. This seems much cleaner to me, wdyt?

**Comment by andydotxyz** [comment]
I think your description above might have "H" and "V" the wrong way round?
The challenge to do what you describe is that widgets have no knowledge of their parents.
Parents can manage children so can this be inverted? I'm not too sure if it is possible given the current architecture unless we combine Entry and ScrollContainer in some way?

I think that I disagree with your idea of combining WrapMaxLines with MultiLine, here is why:
MultiLine could indeed be an int, if you want to specify how many lines the entry should contain - however this is very different to truncating content, it is a rendering that determines the size of the "window" or limits what can be input. However the wrap configuration is indicating when content is too much and so should truncate. As discussed earlier we can't really truncate an entry as the content needs to be completely editable or visible to the user. So I think these are different concepts.
Does that make sense?

**Comment by andydotxyz** [comment]
In chatting on #fyne it occurred to me that the truncating could be implemented in canvas.Text, and the wrapping in widget.textProvider. I don’t know if this makes things easier or not but it is another angle.
When truncating is set then minsize would have to be less horizontally so that the width parameter can cause the clip / ellipsis.

**Comment by stuartmscott** [comment]
I had a re-read and don't my description has "H" and "V" the wrong way round, but I'll try again anyway. In essence there are two directions:
- H - horizontal - content wider than the viewport can be scrolled horizontally (left/right) using a scroll bar on the bottom.
- V - vertical - content taller than the viewport can be scrolled vertically (up/down) using a scroll bar on the side.

Currently Scroller supports both, meaning that an Entry can be scrolled in both directions - no need for truncation or wrapping. However scrolling horizontally makes reading harder and more time consuming. To eliminate this, the entire line of text must be visible within the viewport which is where wrapping comes in - lines wider than the viewport are displayed in multiple rows and additional lines are visible by scrolling vertically. To support this Scroller must support "disabling" of horizontal scrolling so that the Entry's width is forced to match the viewport's and updateRowBounds correctly wraps the lines to fit.

Use cases:
1. EXISTING Entry does not scroll and will grow to fit the text (Entry default).
2. EXISTING Entry inside Scroller can be scrolled in both H and V (Entry+Scroller default).
3. NEW Entry inside Scroller with V disabled can only be scrolled left/right. The Entry's height is determined by (number of rows * text height). The Entry's width is determined by the longest line. I don't think this will be used a lot, but included for consistency.
4. NEW Entry inside Scroller with H disabled can only be scrolled up/down. The Entry's height is determined by (number of rows * text height). The Entry's width will be determined by the wrapping mode:
4a. TextWrapOff - Entry widens to fit all text
4b. TextTruncate - Entry width matches Scroller width, excess text is invisible
4c. TextWrapBreak/TextWrapWord - Entry width matches Scroller width, excess text is wrapped to a new row.

I'm not sure how you can invert this so the parent (Scroller) manages the child (Entry) when the Entry knows the cursor location and need to set the Scroller's offset. Combining Entry and Scroller could work (ScrollableEntry?) however it introduces;
- Confusion - what happens if a ScrollableEntry is placed inside a Scroller?
- Duplication - do Labels and Hyperlinks also get a Scroller combination?

I think "MultiLine bool" should be changed to "MaxLines int" but you're right that it should be separate from "WrapMaxLines int". The former is a limit on the number of lines the model will accept, and the latter is a limit on the number of lines the renderer will display. Perhaps a better name for the latter is "MaxVisibleLines int"?

**Comment by marcoValkyriweb** [comment]
Hi,

MaxDisplayedLines might be better.

**Comment by andydotxyz** [comment]
Both MaxVisibleLines and MaxDisplayedLines could imply something beyond wrap - you could interpret it as limiting the number of newline characters, which is different. Of course if that’s the intent then fine :).

I don’t think that MaxDisplayedColumns is likely to be added - it only makes sense in a monospaced widget and TextGrid is likely to do it much better.

**Comment by stuartmscott** [comment]
So "MultiLine bool" will be changed to "MaxLines int" and limits the number of newline characters;
 - -1 means no limit, have as many newline characters as you want
 - 0 (default) means no newline characters allowed, ie single line entry
 - 1 - MAX_INT means that number of newline characters are allowed

MaxDisplayedLines limits the number of lines (or rows) rendered.

**Comment by andydotxyz** [comment]
I don't think that it's necessary to control the number of newlines separately from the number displayed.
If newline limit was truly required it could be implemented in the app using the widget.

Is the intent of MaxDisplayedLines to define the size of the space required, or to force truncation beyond a size? I am beginning to wonder if perhaps Label and Entry have different requirements in this area. Should we park this discussion for a while, go on without line limits and then review once the basics are landed?

**Comment by stuartmscott** [comment]
Okay, removed MaxNewLines, MaxDisplayedLines, MinDisplayLines and reverted Entry to hardcoded TextAlignLeading.

This PR has brought up a few areas for future work which should get tracked in their own issues;
- Text Justification
- Entry support different Alignments (including cursor handling)
- ScrollContainer support disabling horizontal scrolling
- ScrollContainer support child calling scroll to (x,y)
- Add Text Truncation Ellipsis
- Add Text Wrap Hyphenation

**Comment by andydotxyz** [comment]
Great thanks, on develop for testing
