### ISSUE TITLE
`TableCellID` Parameter in `CreateCell` function call in tree

### ISSUE THREAD

**Issue by ChandanChainani** [fyne-io/fyne#3322]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The feature came to mind due to this question [How to make a table with different object types in fyne-io?](https://stackoverflow.com/questions/73571674/how-to-make-a-table-with-different-object-types-in-fyne-io) over stackoverflow.

It would help to add different widgets without having to depend on `UpdateCell` method which update the cell after it been created we can created 2d slice of widgets and use it in `CreateCell` method to render different widgets

### Describe the solution you'd like to see.

We need to pass `TableCellID` to `CreateCell` as we do in other table methods like `UpdateCell`

**Comment by andydotxyz** [comment]
I don't think this sounds right. If you have created different types of objects there needs to be a whole management of matching created to updated.

If you map 1:1 then the cache is basically unused and we lose performance. To create different types requires a larger change so that the create works with different caches and update is passed the correct type of cached item.

The same mechanism should also work for tree and table.

**Comment by ChandanChainani** [comment]
@andydotxyz Please can you explain how cache is working currently, I am a bit confused not able to understand every part.

**Comment by andydotxyz** [comment]
There is not a page specifically for `Tree` - but its cache works the same as `List` and `Table`, explained here: https://developer.fyne.io/widget/list
