### ISSUE TITLE
The official example lacks interaction

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#3571]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

![WX20230114-205731](https://user-images.githubusercontent.com/1819457/212472747-ea9326a7-0098-48d4-9769-49ca9ecb9eb2.png)

Missing how to interact, how to CURD

### Describe the solution you'd like to see.

It should be added to the operation item, CURD and other interactions

**Comment by junmaqiang** [comment]
Real business requires operations on data, not just display

**Comment by SKBotNL** [comment]
It's supposed to be like that, if you want to know more about tables go to the [documentation](https://developer.fyne.io/widget/table)

**Comment by junmaqiang** [comment]
This question is to ask: How to pass parameters to component methods?

**Comment by junmaqiang** [comment]
`


func list() fyne.CanvasObject {
	t := widget.NewTable(
		func() (int, int) { return 4, 8 },
		func() fyne.CanvasObject {
			return container.NewMax(
				widget.NewLabel("name"),
				widget.NewToolbar(
					widget.NewToolbarSpacer(),
					widget.NewToolbarAction(
						theme.MailComposeIcon(),
						func() { fmt.Println("Click") },
					)))
		},
		func(id widget.TableCellID, cell fyne.CanvasObject) {
			label := cell.(*fyne.Container).Objects[0].(*widget.Label)
			icon := cell.(*fyne.Container).Objects[1].(*widget.Toolbar)
			f := cell.(*fyne.Container).Objects[1].(*widget.Toolbar).Items[1].(*widget.ToolbarAction)
			label.Show()
			icon.Hide()
			switch id.Col {
			case 7:
				label.Hide()
				icon.Show()
				f.OnActivated = getInfoa(id.Row)
			}
		})
}

func getInfoa(a int) {
	fmt.Println("getInfoa:", a)
}
`

**Comment by SKBotNL** [comment]
What doesn't work?

**Comment by Jacalz** [comment]
Please @junmaqiang, use a discussion for questions. This is an issue tracker and intended for reporting bugs and feature requests. I will convert this for you but please use https://github.com/fyne-io/fyne/discussions for questions next time.

I suppose you mean CRUD? If you need to remove or delete items just make sure that the `Length` function (the first passed to `NewTable`) returns the length of a data source instead of hard-coding it to numbers like in the example above. Then you can just remove the item from the slice and call `.Refresh()` on the table.
