### ISSUE TITLE
windows can not run

### ISSUE THREAD

**Issue by xiekong** [fyne-io/fyne#386]
![image](https://user-images.githubusercontent.com/16237228/62459862-0278a200-b7b3-11e9-98c8-9df42de1f7e9.png)

**Comment by Kvaz1r** [comment]
Can you provide more info?
OS version, go version, fyne version? 
Maybe you updated go but not updated properly some packages?

**Comment by metaclips** [comment]
You should probably check this out, https://github.com/fyne-io/fyne/blob/master/README.md#prerequisites

**Comment by andydotxyz** [comment]
Yes, this may be an issue that was fixed in 1.1 (the current release) - if the Fyne installation was from before July then please update.
Otherwise it could relate to multiple graphics cards perhaps - is the machine that you are working on one with an embedded graphics and a secondary, more powerful, card? 
Ticket #191 has more detail about what another person reported and was working on a workaround. Unfortunately none of the developers have a computer with this configuration so it's still an open ticket.

**Comment by xiekong** [comment]
My OS:windows 10
go version
go version go1.12.7 windows/amd64

**Comment by spatocode** [comment]
And fyne version?

**Comment by andydotxyz** [comment]
Yes, the hardware versions you have described @xiekong are supported but the graphics card information is probably critical - can you tell us what make and model is the graphics chip?
There are some hints online about how to do this: https://help.sketchup.com/en/sketchup/how-can-i-find-out-which-graphics-card-i-have-my-pc

**Comment by andydotxyz** [comment]
Request for information 1 year old, closing
