### ISSUE TITLE
Icon set with fyne package is not used by default as Window icon

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#4050]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Packagine with fyne package, with an Icon.png in the same directory.
The Icon.png is set as executable file icon, but not as default Window icon.

### How to reproduce

Build any fyne app, on Windows at least, with fyne package, and provide an Icon.png file.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/1791230/f77a82b9-da95-4b4c-a082-837d9a46e1f2)

### Example code

```go
package main

import "fyne.io/fyne/v2/app"

func main() {
	a := app.New()
	w := a.NewWindow("")

	w.ShowAndRun()
}
```

```toml
[Details]
  Icon = "appicon.png"
  Name = "test"
  ID = "com.test.app"
  Version = "0.0.1"
  Build = 3
```

### Fyne version

v2.3.6-0.20230711075217-36a4286cf62b

### Go compiler version

1.20.4

### Operating system and version

Windows 10

**Comment by Goltanju** [comment]
Hi Andy, I see the same thing here with my apps on Windows. The Icon.png I provide is used for the exe icon but not the window icons. I keep meaning to mention it and forgetting. I just rebuillt a new exe (with a new name and all, just in case) and it behaves the same.

**Comment by matwachich** [comment]
OK, we can close this issue IMO.
It works with develop 2023-07-22

**Comment by Goltanju** [comment]
I wonder what I'm doing wrong then? Still broken for me on 8955ea8 whether I use a FyneApp.toml the --icon option or just let it default to Icon.png.

**Comment by matwachich** [comment]
did you install latest fyne cmd?
go install fyne.io/fyne/v2/cmd/fyne@develop

**Comment by andydotxyz** [comment]
I'm going to look into this more today and see what the status is - I will confirm what versions work to ensure we have it resolved for v2.4.0.

**Comment by Goltanju** [comment]
> I did re-go-install /cmd/fyne and verified which fyne was updated and all.

**Comment by andydotxyz** [comment]
I just checked latest develop on Linux and it is working as expected...

**Comment by Goltanju** [comment]
I tried to find out why it wasn't working here but got lost in the code. It seems that app.NewWindow calls internal/driver/glfw/window.go.createWindow which calls its own type window's SetIcon with nil (I can't see any way it wouldn't be nil there). A nil given to that SetIcon will cause it re-call itself with fyne.CurrentApp().Icon(), unless that's nil, then it does nothing and just returns. I put a debug print in that internal/driver/glfw/window_desktop.go SetIcon to see if fyne.CurrentApp().Icon() ever gave anything not nil there, and it doesn't [for me at least].

So I starting researching fyne.CurrentApp().Icon() onward. Since app is a singleton I just put a panic in SetCurrentApp and started tracing how that got created, paying close attention to anything setting app.icon (I don't think anything ever changes this, just external user code I guess) or anything altering the singleton app.meta.Icon. I did try just changing the AppMetadata.Icon field's name to Icn and recompiling, but that completely succeeded so didn't tell me anything about who might be setting the field, lol.

Not really getting anywhere I then started searching for who calls SetMetadata. Quick greps weren't really fruitful so I just put a panic in app/meta.go's SetMetadata but nothing ever crashed. I even tried renamed the global var meta to see if that would cause any compilation problems but nothing. It was at this point I just gave up, haha.

Not too big a worry as it seems to just be me and I can just embed the icon myself.

**Comment by andydotxyz** [comment]
I can see that this would be confusing. `SetMetadata` is called by generated code that our compiler injects to get FyneApp.toml data or command line arguments into your binary.

That is how the app icon gets bundled and why you're not getting nil from the app icon.
My understanding is that by having the window icon be nil it would use the apps icon - which is what happens in my testing.

**Comment by Goltanju** [comment]
I did see that cmd/fyne/internal/templates/bundled.go calls SetMetadata via the template definition resourceFynemetadatainitGot which is compiled to FyneMetadataInit. That's only used by cmd/fyne/internal/commands/build.go:402

If I place a panic just before that line, rm fyne.exe, go install ./... and then go re `fyne package` the above app with FyneApp.toml and nothing ever panics, the exe icon is fine, the window icon is default. I put in an extra check and, for me at least, the app's icon is also nil.

This is all building on Windows 11 with fyne develop fe90859 using an MSYS2 environment.

A little more research. I put a panic at the top of createMetadataInitFile and nothing seemed to call it here. There is a slightly confusing spot where that func name is shadowed, but no real issue there. Otherwise, seems only build() refererences createMetadataInitFile directly, so I put a panic there and finally saw it. Yay! haha

So that finally released the walls I was hitting and now I know... lol. `if fyneGoModVersion != "master" && !fyneGoModVersionConstraint.Match(fyneGoModVersion)` is the part that's getting me here. My fyneGoModVersion ends up as "v2.0.0-00010101000000-000000000000" and it needs to be ">=2.2". I don't know all the details on go mod, but go mod tidy sets `require fyne.io/fyne/v2 v2.0.0-00010101000000-000000000000` when I have a `replace fyne.io/fyne/v2 => ../fyne` that points to my local fyne repo with develop checked out.

**Comment by andydotxyz** [comment]
You should try latest develop version of the fyne command as I think I fixed something that sounds very similar...

**Comment by andydotxyz** [comment]
However it does imply that your location fyne clone/fork is quite old - you should get numbers like v2.3.6...

**Comment by Goltanju** [comment]
That was with the latest develop branch at the time of that writing.

Here's a fresh walkthrough which you might see where I've made an error:

```
# mkdir empty
# cd empty

# git clone https://github.com/fyne-io/fyne
Cloning into 'fyne'...
remote: Enumerating objects: 70140, done.
remote: Counting objects: 100% (4081/4081), done.
remote: Compressing objects: 100% (1752/1752), done.
remote: Total 70140 (delta 2371), reused 3845 (delta 2305), pack-reused 66059
Receiving objects: 100% (70140/70140), 104.84 MiB | 13.14 MiB/s, done.
Resolving deltas: 100% (46857/46857), done.
Updating files: 100% (2897/2897), done.

# cd fyne
# git checkout develop
branch 'develop' set up to track 'origin/develop'.
Switched to a new branch 'develop'
# git rev-parse HEAD
da074477dfe7f78e5b3198b6f3ed49a2b89b8c87
# cd ..

# mkdir myapp
# cd myapp
# vi main.go
# go mod init myapp
go: creating new go.mod: module myapp
# go mod edit -replace fyne.io/fyne/v2=../fyne
# cat go.mod
module myapp

go 1.20

replace fyne.io/fyne/v2 => ../fyne

# go mod tidy
go: found fyne.io/fyne/v2/app in fyne.io/fyne/v2 v2.0.0-00010101000000-000000000000

# cat go.mod
module myapp

go 1.20

replace fyne.io/fyne/v2 => ../fyne

require fyne.io/fyne/v2 v2.0.0-00010101000000-000000000000

require (
        fyne.io/systray v1.10.1-0.20230722100817-88df1e0ffa9a // indirect
        github.com/davecgh/go-spew v1.1.1 // indirect
        github.com/fredbi/uri v0.1.0 // indirect
        github.com/fsnotify/fsnotify v1.6.0 // indirect
        github.com/fyne-io/gl-js v0.0.0-20220119005834-d2da28d9ccfe // indirect
        github.com/fyne-io/glfw-js v0.0.0-20220120001248-ee7290d23504 // indirect
        github.com/fyne-io/image v0.0.0-20220602074514-4956b0afb3d2 // indirect
        github.com/go-gl/gl v0.0.0-20211210172815-726fda9656d6 // indirect
        github.com/go-gl/glfw/v3.3/glfw v0.0.0-20221017161538-93cebf72946b // indirect
        github.com/go-text/render v0.0.0-20230619120952-35bccb6164b8 // indirect
        github.com/go-text/typesetting v0.0.0-20230616162802-9c17dd34aa4a // indirect
        github.com/godbus/dbus/v5 v5.1.0 // indirect
        github.com/gopherjs/gopherjs v1.17.2 // indirect
        github.com/jsummers/gobmp v0.0.0-20151104160322-e2ba15ffa76e // indirect
        github.com/pmezard/go-difflib v1.0.0 // indirect
        github.com/srwiley/oksvg v0.0.0-20221011165216-be6e8873101c // indirect
        github.com/srwiley/rasterx v0.0.0-20220730225603-2ab79fcdd4ef // indirect
        github.com/stretchr/testify v1.8.0 // indirect
        github.com/tevino/abool v1.2.0 // indirect
        github.com/yuin/goldmark v1.4.13 // indirect
        golang.org/x/image v0.7.0 // indirect
        golang.org/x/mobile v0.0.0-20230427221453-e8d11dd0ba41 // indirect
        golang.org/x/net v0.9.0 // indirect
        golang.org/x/sys v0.8.0 // indirect
        golang.org/x/text v0.9.0 // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect
        honnef.co/go/js/dom v0.0.0-20210725211120-f030747120f2 // indirect
)
```

**Comment by Goltanju** [comment]
I'm pretty sure this is just the way Go works.

`get get` will use the latest version by default, but if adding stuff via `go mod edit -replace` etc. it seems to just use the least version it thinks it can get away with. Not 100% sure there but it doesn't seem unreasonable that I have to be carefully explicit about required versions with replace directives.

So this whole time I have been using the latest code but telling `fyne package` (indirectly via go.mod) that I only wanted v2.0.0. features.

I was just surprised to see the v2.0.0 default required version as I expected the latest version or just a commit hash. Then again, I didn't even think to look at it before as I didn't realize Fyne was using go.mod to determine whether it should include certain features.

With those last two bits of knowledge I am 100% fine with all this, but I can do further exploration if you would like.

**Comment by andydotxyz** [comment]
Perhaps this just won't work with how versions are recorded with replace directives for a local folder?

We will have to look into this a little more, but if that is the case at least the problem is a much narrower case than initially thought.
