### ISSUE TITLE
calling Table.refresh() makes memory usage go up exponentially

### ISSUE THREAD

**Issue by francescoalemanno** [fyne-io/fyne#4333]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.

it seems to be related to #3684

- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Calling Table.refresh() makes memory usage go up exponentially, regardless of garbage collection.
running on win11, msys2 compiler

### How to reproduce

self explanatory

### Example code
        list:=NewTable(A,B,C)
	go func() {
		for {
                        updateListElements()
			list.Refresh()
			time.Sleep(30 * time.Millisecond)
		}
	}()

### Fyne version

2.4.1

### Go compiler version

1.21

### Operating system and version

Win11

**Comment by dweymouth** [comment]
There may certainly be room to further optimize Refresh calls internally, but in general Refresh is an expensive operation and should be only called if the widget's state has changed, and then again at the smallest possible scope, since it means a full re-rendering of the widget is needed. If the widget is just moved or the window is resized for example, then it redraws using cached textures.

**Comment by andydotxyz** [comment]
There will be usage of a texture cache here... if the content has not changed then the cache should be used, but if the content does change that cache will grow.
The clean checks on caches are in minutes not seconds so a tight loop like this could grow a lot in that time.

**Comment by andydotxyz** [comment]
Without more info we should assume this is the text cache working and will improve significantly with the upcoming cache improvements.
Essentially a duplicate or not an issue.
