### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by btagrass** [fyne-io/fyne#4543]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

An error occurred on version v2.4.3.
# fyne.io/fyne/v2/internal/painter
../../go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/font.go:272:84: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight) (exit status 1)

It can work on version v2.2.4

### How to reproduce

go build

### Example code

go build

### Fyne version

v2.3.*,v2.4.*

### Go compiler version

1.21.6

### Operating system and version

Ubuntu 22.04

**Comment by Jacalz** [comment]
Duplicate of #4441, #4443, and #4468. I would recommend searching for the error text on GitHub to avoid opening more issues.

That we can’t compile with a version that we don’t officially support is not a bug in Fyne. My advice is to not blindly update transitive dependencies in your Go modules. Unless you know exactly what has changed and that there are no subtle changes that might introduce bugs or incorrect behaviour, let the package that imports a specific package decide when to update that package.

I.e. never run a bare `go get -u`. If you must update transitive dependencies (for things like security issues), do so on a per package level and not for the whole module.

This will be fixed with an updated release.

**Comment by andydotxyz** [comment]
Just to comment a little further on this - the "don't update all dependencies with -u" is an opinion passed down from the go-text project as well. As part of the collaboration we want to find a way to make it smoother and I believe that we can avoid these problems from our next release. Please bear with us whilst we manage to hide the fact we are using "pre v1" dependencies within our internal code.
