### ISSUE TITLE
Add ability to intercept / veto window close

### ISSUE THREAD

**Issue by seanpringle** [fyne-io/fyne#467]
Is there a way to turn off the "Quit" option added to the gl driver's first main-menu menu?

https://github.com/fyne-io/fyne/blob/0f43af5fe05b6afc09ce8f0c03df1919147e5cd6/internal/driver/gl/menu.go#L33

Alternatively, a way to:

* change the label to allow for language localisation
* specify a custom action function (confirmation, unsaved work dialog, etc)

**Comment by andydotxyz** [comment]
This is a slightly complicated area because macOS, other desktop and mobile devices all handle it differently.

Yes we should support localisation, that needs to be done correctly for the whole framework, however.

There is currently an OnClosed handler on Window that may help - but it seems like what you want is something to fire before closing that determines whether or not it should be allowed? (Is they correct?)

I suspect that configuring the quit menu is not the right approach because the window could be manually closed as well and that should probably trigger the same event..?

**Comment by seanpringle** [comment]
> There is currently an OnClosed handler on Window that may help - but it seems like what you want is something to fire before closing that determines whether or not it should be allowed? (Is they correct?)

Correct.

> I suspect that configuring the quit menu is not the right approach because the window could be manually closed as well and that should probably trigger the same event..?

That sounds logical. Maybe even a general purpose interface for hooking onto window management events?

**Comment by andydotxyz** [comment]
I don’t know if we can really extend it that far as the events vary significantly across platforms. We can certainly add an abstraction where such support makes sense. Starting with WillClose to complement OnClose perhaps? (Unless anyone suggests a better name)

**Comment by seanpringle** [comment]
WillClose sounds great.

**Comment by andydotxyz** [comment]
This was completed a while back :)
