### ISSUE TITLE
Double-click to select a file in FileOpen / FileSave dialogs

### ISSUE THREAD

**Issue by ivoras** [fyne-io/fyne#4676]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

On Windows and Linux at the least, the common way to select a file from a system "select file" dialog is by double-clicking on the file name or icon. Fyne doesn't do this, which makes it counter-intuitive for people used to the native behaviour (a "why isn't the app working?" moment). Mobile environments have their own rules and the current behaviour is fine for them.

### Is it possible to construct a solution with the existing API?

-

### Describe the solution you'd like to see.

Enable confirming file selection in FileOpen / FileSave etc. dialogs by double-clicking on the file name or icon in the list, for desktop environments.

**Comment by Dorbmon** [comment]
@andydotxyz I'd like to implement this feature. But I got a question.
From my understanding, once we listen for the double tapped item, the fyne engine will wait a bit to check if a "tap" event can turn into a "double tapped" event. So it has a great impact on the performance.
Currently, we use grid or list to handle the tapped event. The first thing I think to do is to listen on the tap event on the fileDialogItem (instead of being managed by the grid or list). I think we need to do different thing for the folder item and the file item as the folder doesn't need double tapped event (For better performance) while file item needs it.
Is there a smart way to achieve this instead of declaring two different struct for file and folder?
Thanks.

**Comment by andydotxyz** [comment]
To avoid the delay you can implement the `Mouseable` and `Touchable` interfaces to get info of when the user taps (whereas the `Tapped` event is the higher level abstraction).
I think you can do this equally for file and folder so no need for new types.

**Comment by Dorbmon** [comment]
So I need to check the double tap myself? Like what is done by waitForDoubleTap?

**Comment by andydotxyz** [comment]
> So I need to check the double tap myself? Like what is done by waitForDoubleTap?

A more useful comparison would be the Entry widget where we do lots of more advanced mouse/tap handling.

**Comment by dweymouth** [comment]
Fixed on develop for release 2.5.0
