### ISSUE TITLE
Default text for input(Entry) widget

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#470]
**Is your feature request related to a problem? Please describe.**

MCVE:

```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {

	app := app.New()
	w := app.NewWindow("MCVE")
	w.Resize(fyne.Size{800, 600})

	out := widget.NewEntry()
	out.Text = "Hello"

	w.SetContent(widget.NewVBox(
		out))

	w.ShowAndRun()
}
```

There isn't "Hello" text after creation. It really useful as hint for user input.

**Is it possible to construct a solution with the existing API?**
I don't found a way to do it, but not sure at 100%. 

**Describe the solution you'd like**
Provide way to set default value for input(Entry) widget.

**Comment by hundredwz** [comment]
I think you can try 
```
out.SetText("Hello")
```
this should work

**Comment by Kvaz1r** [comment]
Yes, it works.

**Comment by andydotxyz** [comment]
Direct property access is primarily used for constructing widgets, so the setter (SetText()) is better for modifying values as it calls refresh to enact the change. You can change values directly if you wish but calling widget.Refresh(myWidget) afterward is required to apply the change.

If you are looking for a user hint, however, I would recommend SetPlaceholderText() as that behaves as a placeholder so that an empty value is returned if you get the text later :).
