### ISSUE TITLE
when dialog.ShowFileOpen then  click cancel，window quit and program terminated

### ISSUE THREAD

**Issue by AncestorDragon** [fyne-io/fyne#4833]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

GOVERSION=go1.22.2
fyne.io/fyne/v2 v2.4.5
os: Windows

when dialog.ShowFileOpen then  click cancel，window quit and program terminated

### How to reproduce

when dialog.ShowFileOpen then  click cancel，window quit and program terminated

### Example code

	button := widget.NewButton("aaa", func() {
		dialog.ShowFileOpen(func(f fyne.URIReadCloser, err error) {
			fmt.Println(f.URI().Path())
			filePath = f.URI().Path()
		}, myWindow)
	})

### Fyne version

fyne.io/fyne/v2 v2.4.5

### Go compiler version

go1.22.2

### Operating system and version

Windows

**Comment by Jacalz** [comment]
This is not a bug. The documentation for the function (https://pkg.go.dev/fyne.io/fyne/v2/dialog#ShowFileOpen) notes that it will return `nil` for the file when none is selected. I.e. your application is crashing because you are not checking if `f` is nil. While likely not the issue here, you will probably run into even more issue given that you aren’t checking the error.
