### ISSUE TITLE
Entry in HBox can't set size

### ISSUE THREAD

**Issue by eliohn** [fyne-io/fyne#4879]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

![1716730336352](https://github.com/fyne-io/fyne/assets/5205873/e8f18bba-942e-424a-8ef1-6f71c05629ed)

### How to reproduce

Build new window,

### Example code

`package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry in HBox")
	myWindow.Resize(fyne.NewSize(400, 300))

	entry := widget.NewEntry()
	entry.Resize(fyne.NewSize(200, 30)) // 设置Entry的大小

	hBox := container.NewHBox(
		layout.NewSpacer(),
		entry,
		layout.NewSpacer(),
	)
	myWindow.SetContent(hBox)
	myWindow.ShowAndRun()
}`

### Fyne version

2.4.5

### Go compiler version

1.22.0

### Operating system and version

Windows 10

**Comment by dweymouth** [comment]
An HBox by design makes widgets lay out at their minimum width. You are looking for a different layout, maybe Border. Also, you cannot manually resize widgets using `.Resize()` unless you are putting them in a container without layout. In a regular container with a layout, the layout calls `.Resize()` and `.Move()` on the widgets for you.
