### ISSUE TITLE
Closing a secondary window destroys the object so it cannot be re-used

### ISSUE THREAD

**Issue by cjbrowne** [fyne-io/fyne#522]
**Describe the bug**
Using `application.NewWindow` to create a secondary window, it's not possible to re-use that window after it has been closed.  If the user presses the X button, the window doesn't respond to Show() calls any more.

**To Reproduce**
1. Create a main window
2. Create a secondary window
3. Close the secondary window
4. Attempt to re-show the secondary window.

Example code:
```
func main() {
  application := app.New()
  mainWindow := application.NewWindow("main")
  secondaryWindow := application.NewWindow("secondary")
  mainWindow.SetContent(widget.NewButton("TEST", func () {
    secondaryWindow.Show()
  }))
  mainWindow.ShowAndRun()
}
```

Given the example program, click the "TEST" button, then close the sub-window, then click the "TEST" button a second time.  The sub-window does not come back.

**Screenshots**

**Device (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Go version: 1.13
 - Fyne version: 1.1.2

**Comment by spatocode** [comment]
Am not sure why this bug exists, but you should create a new window from the current application, for which there's 1 per process. This should work fine.

func main() {
  application := app.New()
  mainWindow := application.NewWindow("main")
  secondaryWindow := fyne.CurrentApp().NewWindow("secondary")
  mainWindow.SetContent(widget.NewButton("TEST", func () {
    secondaryWindow.Show()
  }))
  mainWindow.ShowAndRun()
}

**Comment by cjbrowne** [comment]
ah! ok, I didn't realise that.

Thanks for your help :D

**Comment by andydotxyz** [comment]
The suggested code is identical - fyne.CurrentApplication() will return the result of previously called app.New().

Though I would like to hear from @cjbrowne to confirm I am pretty sure this is still an open issue, so am reopening.

**Comment by cjbrowne** [comment]
I'll do some testing today, I will admit I didn't actually check that the suggested code works.

**Comment by spatocode** [comment]
Sorry @cjbrowne, the code is really identical(apologies). But, @andydotxyz it seems the suggested piece of code works only on the fyne demo app. Something is not quite right.

**Comment by andydotxyz** [comment]
Sorry, I’m not sure if you are reporting a new issue - can you confirm what doesn’t work outside the demo app? Thanks

**Comment by spatocode** [comment]
I'm not pretty sure this is a bug. When you create a secondary window outside the button callback, that window object is stored in memory. Now, when you close the window, that window is destroyed so the window object in memory may not be reused(show) again. The proper way is to create the secondary window inside the button callback function so that a new window object is created each time the button is clicked.

This should work fine

func main() {
  application := app.New()
  mainWindow := application.NewWindow("main")
  mainWindow.SetContent(widget.NewButton("TEST", func () {
    secondaryWindow := application.NewWindow("secondary")
    secondaryWindow.Show()
  }))
  mainWindow.ShowAndRun()
}

**Comment by andydotxyz** [comment]
It should not matter how or when you create a new window (inside or outside of a callback).
Your demo code @spatocode is creating a new one every time, which will always work.

I think that @cjbrowne still has a point - a window that is hidden could easily want to be shown again and any state associated will be lost if we continue to delete the window when it is hidden instead of identifying the difference between Hide and Close/Destroy.

**Comment by andydotxyz** [comment]
I have looked at this some more and come to the conclusion that a user close-action is showing the intent to not re-use the window. Perhaps this relates to #467? If that were added you could override the default close behaviour somehow.

If you were to manually call `Window.Hide()` then it could be re-used, but Closing a window is like calling `Window.Close()` which destroys content.
Unless any objection I think this issue should be closed as won't-fix as the behaviour is correct.
