### ISSUE TITLE
Access to children of Group widget

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#541]
**Is your feature request related to a problem? Please describe.**
Accessing contents of group widgets seems impossible as its a private variable

**Describe the solution you'd like**
either
1. Children pointer be public and be accessible both to Group struct and box variable, or
2. Box variable in Group struct be made public

**Comment by andydotxyz** [comment]
The box is an implementation detail so we should not expose that. To do this properly may require rewriting the group widget to not delegate to box as much.

What are you trying to do, perhaps there is a workaround we could figure out in the meantime?

**Comment by metaclips** [comment]
I'm trying to access Group widgets contents passed to a function parameter, I instead passed all contents to a Box widget which was then passed to the group widget, I then accessed all contents on group directly from the boxs children instead. I guess this should suffice till a rewrite to the Group widget. Thanks.

**Comment by andydotxyz** [comment]
That's more of how you are trying to do it than what you're trying to achieve ;).
I am asking because I wonder if this is related to data binding or if there is something else we should be considering.
It just seems a little strange to be passing a group widget around as it's more of a visual construct...

**Comment by metaclips** [comment]
Yup, I need to be able to update contents in the the group widget at real time then perform a refresh.

**Comment by andydotxyz** [comment]
Do you have any more information about the sort of data that you are using or why you want to pass a widget list to the function instead of managing the widgets directly?
I'm glad you have a workaround at the moment but I am still curious if this is something we should solve through data API instead of a Group widget rewrite.

**Comment by metaclips** [comment]
I am trying to access labels passed in Boxs' to the group widget, I need to be able to call the group's widget children then access the contents using interfaces as passing all labels would be cumbersome and list content could be appended to also.

**Comment by andydotxyz** [comment]
We decided that Group (and Box) APIs are broken. They have been replaced by `widget.Card` (a more Material Design version of Group) and `container.New[H/V]Box` which creates a container using box layout instead of a new widget.
Hopefully you can work with one of these in 1.4. The old APIs will remain until 2.0 but we cannot solve the issue originally requested in this ticket.
