### ISSUE TITLE
Emojis Support

### ISSUE THREAD

**Issue by dhinojosac** [fyne-io/fyne#573]
Add support for emojis in Labels or EntryText, this would server to make a chat application.

**Comment by andydotxyz** [comment]
Oh yes, this is a great thing to add.
We would have to embed the font/images to handle this however so size may be an issue.
Does anyone know of a great source of BSD compatible freely usable images that we could base this on?

**Comment by dhinojosac** [comment]
Could this help? https://twemoji.twitter.com/

**Comment by andydotxyz** [comment]
It could do - but the attribution may be a problem. We’d need to have all apps using Fyne mention that they use the twitter emoji set. They may be lenient on that but we’d probably need special permission to not push that on to developers.

**Comment by aksdb** [comment]
You are already using the noto fonts, right? So shouldn't that tick all the necessary boxes?
https://github.com/googlefonts/noto-emoji

**Comment by andydotxyz** [comment]
That is a good point, I'm not sure how I forgot they had one.
Now we just need to figure out how to manage the size of the additional data!

**Comment by aksdb** [comment]
I was just looking into the current font rendering code. If I don't miss anything, there is currently no way to merge fonts in memory, right? (I think that's how some of the bigger UI frameworks handle that stuff.)

So I guess long-term it would be cool to to have that ability. That would also solve some unicode problems or allow custom icons to be included. This would mean some theme specific "font inclusions" or something like that.

Short term it would probably be enough to have #808 implemented, because then it would be possible to have a plugin (separate package) that includes an emoji component. This one can reference a static resource bundled only within that package. If you don't need emojis, don't include it. If you need them, you have to separate them from the text and add them as separate text objects.

**Comment by andydotxyz** [comment]
We do have font merging internally (`internal/painter/font.go`) so that a FYNE_FONT configuration does not break english. The same approach could indeed be used to handle emoji. Kerning probably gets more complicated but it should be possible.

**Comment by andydotxyz** [comment]
I tested the noto emoji fonts and there is clearly more work to do than just load the font.
The colour emojis (that we expect) don't render with the current font renderer.
The monochrome one seems to work... but it breaks our space calculations!

<img width="266" alt="Screenshot 2020-05-09 at 22 03 23" src="https://user-images.githubusercontent.com/294436/81484873-191bc000-9241-11ea-9a8d-8094e3cdf7a3.png">

**Comment by UrbiJr** [comment]
+1 to add Emojis support. Nowadays I think it's essential for a modern app to have them.
Let alone if one wants to build an integrated chat.
It's ok to not integrate them per default, but can we have a guide to add emoji support manually?

**Comment by andydotxyz** [comment]
It must be added at the toolkit level to integrate in text. Emoji (at least the coloured ones we see everywhere) are pngs embedded in a font file, and our font rendering does not support that yet.

**Comment by jobukkit** [comment]
PNG's embedded in a font file are just one format, other formats are SVG's embedded in a font file or that colour layer system Microsoft uses. You can implement the one that's easiest for how your font rendering works and then include a compatible font.

**Comment by andydotxyz** [comment]
Indeed so, perhaps I was too specific. What I mean is that our font rendering currently is just for textual info and not the images that emoji needs (though the black and white glyph ones should work, if you bundle/load a font file).

**Comment by andydotxyz** [comment]
Oh this was completed and will be released in v2.4.0.

<img width="215" alt="emoji2" src="https://github.com/fyne-io/fyne/assets/294436/802c167b-f730-4989-ab18-6e503154c98e">
