### ISSUE TITLE
Android and iOS

### ISSUE THREAD

**Issue by ghost** [fyne-io/fyne#65]
The base framework can probably be compiled to ndk and iOS as a shared lib.
Then go can be be compiled against it.

Or the traditional root of using gomonile but I think it will be too limiting.

Either way it is worth trying out.

**Comment by andydotxyz** [comment]
Mobile is on the cards for the framework in the future.
As well as the compilation we would need to add some platform support - iOS and Android will handle certain things differently to desktop systems and we want to work seamlessly :)

**Comment by hubyhuby** [comment]
There is also android-go project that could be a good fite. They have managed to launch Nuklear already.
https://github.com/xlab/android-go

**Comment by andydotxyz** [comment]
Great hint. Once we resolve #239 then we could look at mobile platforms properly.

**Comment by hubyhuby** [comment]
Hi @andydotxyz ,
I have asked on Max's project and he seems looking forward to give it a try :
https://github.com/xlab/android-go/issues/29

**Comment by andydotxyz** [comment]
There is a new branch named feature/android where we have early versions of an android driver running.
It’s using gomobile for now until we hit its limits. The nice thing is that you can use “go build” to compile a desktop app or “gomobile build” to build a mobile app. Exact same app code :). This will be released in 1.2 later in the year.

**Comment by andydotxyz** [comment]
Trying too capture those things required to complete mobile support:

- [ ]  Add display driver for iOS and Android
- [ ]  Set up a tap handler for mobile (including secondary = tap-hold)
- [ ]  Support of tap-to-scroll gesture
- [ ]  Add device API covering the type of device, it's orientation and whether it has a keyboard
- [ ]  Update tabcontainer design to match expectations on mobile (top or bottom in vertical and something clever in landscape)
- [ ]  Reconfigure the view and refresh on rotation
- [ ]  Determine global settings from the device instead of fyne config file
- [ ]  Correct padding around the screen to accomodate iOS and android device hardware
- [ ]  Support a burger-style menu arrangement if MainMenu is set
- [ ]  Handle multiple windows by adding a back / title bar that will close the window when tapping back

**Comment by andydotxyz** [comment]
Removed TODO item duplicated in #413

**Comment by andydotxyz** [comment]
Moved theme detection to #472 as the APIs are it required brand new devices so not very common yet.

**Comment by andydotxyz** [comment]
That’s all the items in this ticket in.
Still no keyboard support but that is in a separate ticket
