### ISSUE TITLE
Recommended technique for embedding an executable within the Fyne UI

### ISSUE THREAD

**Issue by rootVIII** [fyne-io/fyne#692]
### Is your feature request related to a problem? Please describe:

There's no problem. I'm just curious if there's a recommended or possible way to open and run an executable (and display it's UI) from within the Fyne UI.

### Is it possible to construct a solution with the existing API?

I am able to os/exec a separate executable of course. However I would like to position it within a widget or canvas object etc. instead of having it float around.

### Describe the solution you'd like to see:

I am specifically trying to embed a plain old bash shell within my Fyne UI/app.  I'm sure it's already possible somehow after watching the Game Boy demo. Any tips are appreciated. Thanks!

**Comment by andydotxyz** [comment]
I'm really sorry but due to the various display technologies (amongst other issues) this is not a trivial task.

The only real approach that could work with "any embed" would be to find a way to capture (i.e. get the rendered output of) the software you want to embed - and then display that inside a widget. You would also have to capture all the key presses or mouse inputs and channel them back to the application, It's not really something that has a generic solution unfortunately.

That said if what you want is an embedded terminal then we have some good news. We are starting a terminal widget that will be embeddable in any fyne application. It will not become part of the core library as it's platform specific but this is probably the closest solution to what you want..?

**Comment by rootVIII** [comment]
oh yeah sounds great! Thanks!
