### ISSUE TITLE
Usage of `fyne.io/fyne/internal/cache` makes it hard to write custom widgets by copy pasting library code.

### ISSUE THREAD

**Issue by DerThorsten** [fyne-io/fyne#696]
I wanted to extend the Select widget st. the individual options can have different colors.
Since the this would require changes to the widgets renderer I cannot just extend the `Select` widget, but I would need to extend the widgets renderer which is private  (`selectRenderer`).
Since the whole file implementing the Select widget is only **~200** lines of code I thought I could just copy/paste the `select.go` file into my own package and implement the needed changes there.
But the **usage** of **`fyne.io/fyne/internal/cache`** makes this impossible (use of internal package fyne.io/fyne/internal/cache not allowed).

Is it so important to to disallow the importing of the `cache` package that is justifies this?
I think without this limitation it would be way easier to write custom widgets, since one could just copy/paste from the library code and one would have a **good starting point** for **non-trivial** custom widgets.

Greetings

**Comment by DerThorsten** [comment]
Furthermore, If writing widgets of the **same quality** as the libraries build in widgets requires usage of `internal` packages, it is **impossible** to write custom widgets of the same quality.

**Comment by andydotxyz** [comment]
This is a complex question. The quick answer is that yes it is important that people don't access this cache - because we plan to deprecate it. The widgets (mainly Select and ProgressBar) that rely on it are historical issues that we have not yet improved upon.

We are aware of this frustration and @toaster is actually working on it right now :)

Unfortunately at this time the type of extension that is supported is to add functionality rather than changing how they look. It is our intention to expand this and any help or input would be appreciated :)

**Comment by andydotxyz** [comment]
The design of the toolkit is moving more towards extension where possible or building your own from scratch. I don't think we can realistically support copying out code from the package and have no internal reference.
