### ISSUE TITLE
WebView widget possibility?

### ISSUE THREAD

**Issue by gdeverlant** [fyne-io/fyne#744]
Greetings dear talented contributors for this wonderful project :D 

I would like to know how complicated would it be to have somehow an HTML Webview Renderer to be able to inject either static sites or Single Application Page inside of Fyne.

I don't know if this could help but I found out this amazing binding with Ultralight UX in golang and it seems to be a good candidate for Fyne. But I don't know if Fyne rendering cycle can be mixed with Ultralight UX. https://github.com/ImVexed/muon

Please enlighten me for this nebulous question.

Best regards

**Comment by andydotxyz** [comment]
This has been discussed on a few previous tickets, initially on #116 basically the answer is that this is unlikely to happen.
Partly the issue is that we do not want to introduce dependencies and this, when combined with our permissive licensing, means that such a widget is highly unlikely to enter the main repository.
Additionally we don't think that embedding web content is right for our vision of a performant, native toolkit.

**Comment by gdeverlant** [comment]
My apologies for duplicate.

**Comment by andydotxyz** [comment]
Not a problem, just thought I would point you to our previous discussion

**Comment by yuseferi** [comment]
That is sad :(
