### ISSUE TITLE
[Question] Set rectangle height and width

### ISSUE THREAD

**Issue by talentlessguy** [fyne-io/fyne#929]
Hello, I am new to Fyne and couldn't find the answer neither in tour, nor in docs.

What's the proper way of setting height and width to a rectangle?

I want to make a custom progress bar and I want to make 2 rectangles, one with absolute and another with relative position.

I stuck on something like this but it doesn't work:

```go
package main

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
)

// NewAudioBar - track bar
func NewAudioBar(currentTime int, timeLeft int) *fyne.Container {
	progressBar := &canvas.Rectangle{
		StrokeColor: color.White,
		StrokeWidth: 10,
	}
	totalBar := &canvas.Rectangle{
		StrokeColor: color.Black,
		StrokeWidth: 10,
	}
	return fyne.NewContainerWithLayout(layout.NewVBoxLayout(), progressBar, totalBar)
}
```

Would be cool to see if there is any good example of custom rectangle elements :D

**Comment by LuSaxy** [comment]
if i had to change your code - and i am a noob, but i would most likely create a container with grid layout and make 100 grid items. then i would do a calculation to say how much of the song is completed and then make x blocks of colour white and 100-x as colour black. and then return that container.

that having been said - it probably isnt the best idea because you are creating a new container each time. and alternative is to create and set text with colour. so you can use ascii values to have full colour blocks and set the text color and text size. then each time you just update the text and the bar will auto change by itself without having to return a new container <- in my experience replacing objects with new objects arent the greatest if you are doing them constantly

**Comment by LuSaxy** [comment]
Hi,

i got something to work. i can try clean it up when i have a little time and send it to you but essentially:
1) your NewVBoxLayout needs to be New**H**BoxLayout, H= Horizontal for adding the 2 rectangles.
2) you then set each rectange as a variable of type *fyne.rectangle so you can reference it each time. you need to also set the size of the rectangle or else it will collapse on itself and just give you 2 dots. so progressbar.resize() or something
3) whenever you want to do sizing changes. just say rectangle1.resize and set the width to what you want it, and then rectangle2.resize as total - rectangle1 as the width.

i tested with a go routine that every second just resized it. and it worked. you will most likely just need a type to hold the container and rectangles in, so that you can easily reference. will work on a an example

**Comment by LuSaxy** [comment]
This does the basics. you can play around with it to do what you want it to do
```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
	"golang.org/x/image/colornames"
	"image/color"
	"time"
)

type ProgressBox struct {
	rectangleLeft *canvas.Rectangle
	rectangleRight *canvas.Rectangle
	container *fyne.Container
}

func NewProgressBox(color color.Color) (box *ProgressBox){
	rectangleLeft:= canvas.NewRectangle(color)
	rectangleRight := canvas.NewRectangle(colornames.Black)
	rectangleRight.Resize(fyne.Size{
		Width:  0,
		Height: 10,
	})
	rectangleRight.Resize(fyne.Size{
		Width:  100,
		Height: 10,
	})
	box=&ProgressBox{
		rectangleLeft: rectangleLeft,
		rectangleRight: rectangleRight,
		container: fyne.NewContainerWithLayout(layout.NewHBoxLayout(), rectangleLeft, rectangleRight),
	}
	return box
}

func SummaryScreen() fyne.CanvasObject{
	screen :=widget.NewVBox()
	box:=fyne.NewContainerWithLayout(layout.NewGridLayout(4))
	screen.Append(box)
	Progress1:=NewProgressBox(colornames.Whitesmoke)

	box.AddObject(Progress1.container)
	box.AddObject(widget.NewLabel("check"))
	go func() {
		for i:=1;i<100;i++{
			Progress1.rectangleRight.SetMinSize(fyne.Size{
				Width:  100-i,
				Height: 10,
			})
			Progress1.rectangleLeft.SetMinSize(fyne.Size{
				Width:  i,
				Height: 10,
			})
		time.Sleep(time.Second)
			canvas.Refresh(screen)
		}
	}()



	return screen
}


var GUIApp = app.New()
var GUIWindow = GUIApp.NewWindow("Colors")

func main(){
	tabs := widget.NewTabContainer(
		widget.NewTabItemWithIcon("BAR", theme.HomeIcon(), SummaryScreen()),)
	tabs.SetTabLocation(widget.TabLocationLeading)
	tabs.Resize(fyne.NewSize(100, 600))
	GUIWindow.Resize(fyne.NewSize(1200, 600))
	GUIWindow.SetContent(tabs)
	GUIWindow.ShowAndRun()

}

```

**Comment by andydotxyz** [comment]
You have placed the items in a VBox, and so that will manage their size. From the tour page on Containers and Layouts: https://tour.fyne.io/basics/container.html 

> In this example we create 3 text objects and then place them in a container using the NewContainer() function. As there is no layout set we can move the elements around like you see with text2.Move().

Therefore if you want to manage item size and position manually you should not specify a layout. More correct is normally to define a layout that does what you want (layouts will be told to adjust when windows resize, whereas manually coded positions don't get that information).

If you are interested in how a progress bar is written I would recommend the code for the builtin progress bar. https://github.com/fyne-io/fyne/blob/master/widget/progressbar.go

**Comment by andydotxyz** [comment]
In your example @LuSaxy you are specifying MinSize changes - this is different again. The Box you have placed the items in is managing the size but you are forcing the items to larger each time through expanding the minsize...

**Comment by talentlessguy** [comment]
@andydotxyz so I suppose the best way is not setting widths and heights but paddings instead?

**Comment by andydotxyz** [comment]
Sorry but I don't see what you mean by padding... why would padding help with sizing items?
In Fyne land padding is what exists between widgets and is set to a standard amount by the theme.

The "right way" is normally to write a layout or to build a widget, who's renderer encapsulates an appropriate layout method.

**Comment by talentlessguy** [comment]
@andydotxyz is there any example of setting rectangle dimensions the right way? I'm new to Fyne but have frontend background and that's why I ask weird things :c

**Comment by andydotxyz** [comment]
If you are trying to build a progress bar I would recommend reading the code to our progress bar that I linked above.
I think that we have provided a few possible answers, unless you have more specific questions I'm not sure what can be added to help. It's possible you have overlooked the Rectangle.Resize() method but that seems unlikely.

**Comment by talentlessguy** [comment]
Sooo I made this work! Thanks for help @andydotxyz, I tried to read source code of progress bar and came up with this:

![image](https://user-images.githubusercontent.com/35937217/81163472-7c82c500-8f97-11ea-85fc-5fb6260dda30.png)

code:

```go
package main

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/theme"
)

// NewAudioBar - track bar
func NewAudioBar(currentTime int, timeLeft int) *fyne.Container {
	currentBar := canvas.NewRectangle(theme.PrimaryColor())

	totalBar := canvas.NewRectangle(color.Black)

	currentBar.Resize(fyne.NewSize(100, 10))

	totalBar.Resize(fyne.NewSize(350, 10))

	c := fyne.NewContainer(totalBar, currentBar)

	return c
}
```
