### ISSUE TITLE
defaultPlaceHolder problem

### ISSUE THREAD

**Issue by prifre** [fyne-io/fyne#967]
### widget.Select not narrow enough...
in fyne.io/fyne/widget/select.go, line 13

const defaultPlaceHolder string = "(Select one)"

prevents to have a narrower selection menu than len( "(Select one)")

(I solved the problem by patching the const to ""... not pretty, byt works...)

### Example code:
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.NewWithID("")
	w := a.NewWindow("")
	s2 := []string{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"}
	wi := widget.NewSelect(s2, func(s string) {})
	wi.SetSelected("1")	// this SHOULD have made it narrow?
	wi.PlaceHolder = "" // this SHOULD have made it narrow?
	w.SetContent(wi)
	w.ShowAndRun()
}

### Device 
Using Windows 10... Go 
 - Version: [e.g. 22]
 - Go version: go version go1.14.1 windows/amd64
 - Fyne version: the latest available at date 2020-05-10

**Comment by andydotxyz** [comment]
You're right - `wi.PlaceHolder = ""` should have made it smaller.
If you have the longer placeholder it will leave that size reserved in case it needs to be displayed.
In our next release the shorter placeholder will correctly result in a smaller minimum size.
1.3 release is currently due to release on June 1st.
